/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita-swift
 */
import Foundation
import Beet
import Solana

/**
 * @category Instructions
 * @category AuctioneerCancel
 * @category generated
 */
public struct AuctioneerCancelInstructionArgs{
    let instructionDiscriminator: [UInt8] /* size: 8 */
    let buyerPrice: UInt64
    let tokenSize: UInt64

    public init(
        instructionDiscriminator: [UInt8] /* size: 8 */ = auctioneerCancelInstructionDiscriminator,
        buyerPrice: UInt64,
        tokenSize: UInt64
    ) {
        self.instructionDiscriminator = instructionDiscriminator
        self.buyerPrice = buyerPrice
        self.tokenSize = tokenSize
    }
}
/**
 * @category Instructions
 * @category AuctioneerCancel
 * @category generated
 */
public let auctioneerCancelStruct = FixableBeetArgsStruct<AuctioneerCancelInstructionArgs>(
    fields: [
        ("instructionDiscriminator", Beet.fixedBeet(.init(value: .collection(UniformFixedSizeArray<UInt8>(element: .init(value: .scalar(u8())), len: 8))))),
        ("buyerPrice", Beet.fixedBeet(.init(value: .scalar(u64())))),
        ("tokenSize", Beet.fixedBeet(.init(value: .scalar(u64()))))
    ],
    description: "AuctioneerCancelInstructionArgs"
)
/**
* Accounts required by the _auctioneerCancel_ instruction
*
* @property [_writable_] wallet  
* @property [_writable_] tokenAccount  
* @property [] tokenMint  
* @property [] authority  
* @property [**signer**] auctioneerAuthority  
* @property [] auctionHouse  
* @property [_writable_] auctionHouseFeeAccount  
* @property [_writable_] tradeState  
* @property [] ahAuctioneerPda   
* @category Instructions
* @category AuctioneerCancel
* @category generated
*/
public struct AuctioneerCancelInstructionAccounts {
    let wallet: PublicKey
    let tokenAccount: PublicKey
    let tokenMint: PublicKey
    let authority: PublicKey
    let auctioneerAuthority: PublicKey
    let auctionHouse: PublicKey
    let auctionHouseFeeAccount: PublicKey
    let tradeState: PublicKey
    let ahAuctioneerPda: PublicKey
    let tokenProgram: PublicKey?

    public init(
        wallet: PublicKey,
        tokenAccount: PublicKey,
        tokenMint: PublicKey,
        authority: PublicKey,
        auctioneerAuthority: PublicKey,
        auctionHouse: PublicKey,
        auctionHouseFeeAccount: PublicKey,
        tradeState: PublicKey,
        ahAuctioneerPda: PublicKey,
        tokenProgram: PublicKey? = nil
    ) {
        self.wallet = wallet
        self.tokenAccount = tokenAccount
        self.tokenMint = tokenMint
        self.authority = authority
        self.auctioneerAuthority = auctioneerAuthority
        self.auctionHouse = auctionHouse
        self.auctionHouseFeeAccount = auctionHouseFeeAccount
        self.tradeState = tradeState
        self.ahAuctioneerPda = ahAuctioneerPda
        self.tokenProgram = tokenProgram
    }
}

public let auctioneerCancelInstructionDiscriminator = [197, 97, 152, 196, 115, 204, 64, 215] as [UInt8]

/**
* Creates a _AuctioneerCancel_ instruction.
*
* @param accounts that will be accessed while the instruction is processed
  * @param args to provide as instruction data to the program
 * 
* @category Instructions
* @category AuctioneerCancel
* @category generated
*/
public func createAuctioneerCancelInstruction(accounts: AuctioneerCancelInstructionAccounts, 
args: AuctioneerCancelInstructionArgs, programId: PublicKey=PublicKey(string: "hausS13jsjafwWwGqZTUQRmWyvyxn9EQpqMwV1PBBmk")!) -> TransactionInstruction {

    let data = auctioneerCancelStruct.serialize(
            instance: ["instructionDiscriminator": auctioneerCancelInstructionDiscriminator,
"buyerPrice": args.buyerPrice,
  "tokenSize": args.tokenSize])

    let keys: [AccountMeta] = [
        AccountMeta(
            publicKey: accounts.wallet,
            isSigner: false,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.tokenAccount,
            isSigner: false,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.tokenMint,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.authority,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.auctioneerAuthority,
            isSigner: true,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.auctionHouse,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.auctionHouseFeeAccount,
            isSigner: false,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.tradeState,
            isSigner: false,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.ahAuctioneerPda,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.tokenProgram ?? PublicKey.tokenProgramId,
            isSigner: false,
            isWritable: false
        )
    ]

    let ix = TransactionInstruction(
                keys: keys,
                programId: programId,
                data: data.0.bytes
            )
    return ix
}