/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita-swift
 */
import Foundation
import Solana
import Beet

/**
 * @category Instructions
 * @category Cancel
 * @category generated
 */
public struct CancelInstructionArgs{
    let instructionDiscriminator: [UInt8] /* size: 8 */
    let buyerPrice: UInt64
    let tokenSize: UInt64

    public init(
        instructionDiscriminator: [UInt8] /* size: 8 */ = cancelInstructionDiscriminator,
        buyerPrice: UInt64,
        tokenSize: UInt64
    ) {
        self.instructionDiscriminator = instructionDiscriminator
        self.buyerPrice = buyerPrice
        self.tokenSize = tokenSize
    }
}
/**
 * @category Instructions
 * @category Cancel
 * @category generated
 */
public let cancelStruct = FixableBeetArgsStruct<CancelInstructionArgs>(
    fields: [
        ("instructionDiscriminator", Beet.fixedBeet(.init(value: .collection(UniformFixedSizeArray<UInt8>(element: .init(value: .scalar(u8())), len: 8))))),
        ("buyerPrice", Beet.fixedBeet(.init(value: .scalar(u64())))),
        ("tokenSize", Beet.fixedBeet(.init(value: .scalar(u64()))))
    ],
    description: "CancelInstructionArgs"
)
/**
* Accounts required by the _cancel_ instruction
*
* @property [_writable_] wallet  
* @property [_writable_] tokenAccount  
* @property [] tokenMint  
* @property [] authority  
* @property [] auctionHouse  
* @property [_writable_] auctionHouseFeeAccount  
* @property [_writable_] tradeState   
* @category Instructions
* @category Cancel
* @category generated
*/
public struct CancelInstructionAccounts {
    let wallet: PublicKey
    let tokenAccount: PublicKey
    let tokenMint: PublicKey
    let authority: PublicKey
    let auctionHouse: PublicKey
    let auctionHouseFeeAccount: PublicKey
    let tradeState: PublicKey
    let tokenProgram: PublicKey?

    public init(
        wallet: PublicKey,
        tokenAccount: PublicKey,
        tokenMint: PublicKey,
        authority: PublicKey,
        auctionHouse: PublicKey,
        auctionHouseFeeAccount: PublicKey,
        tradeState: PublicKey,
        tokenProgram: PublicKey? = nil
    ) {
        self.wallet = wallet
        self.tokenAccount = tokenAccount
        self.tokenMint = tokenMint
        self.authority = authority
        self.auctionHouse = auctionHouse
        self.auctionHouseFeeAccount = auctionHouseFeeAccount
        self.tradeState = tradeState
        self.tokenProgram = tokenProgram
    }
}

public let cancelInstructionDiscriminator = [232, 219, 223, 41, 219, 236, 220, 190] as [UInt8]

/**
* Creates a _Cancel_ instruction.
*
* @param accounts that will be accessed while the instruction is processed
  * @param args to provide as instruction data to the program
 * 
* @category Instructions
* @category Cancel
* @category generated
*/
public func createCancelInstruction(accounts: CancelInstructionAccounts, 
args: CancelInstructionArgs, programId: PublicKey=PublicKey(string: "hausS13jsjafwWwGqZTUQRmWyvyxn9EQpqMwV1PBBmk")!) -> TransactionInstruction {

    let data = cancelStruct.serialize(
            instance: ["instructionDiscriminator": cancelInstructionDiscriminator,
"buyerPrice": args.buyerPrice,
  "tokenSize": args.tokenSize])

    let keys: [AccountMeta] = [
        AccountMeta(
            publicKey: accounts.wallet,
            isSigner: false,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.tokenAccount,
            isSigner: false,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.tokenMint,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.authority,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.auctionHouse,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.auctionHouseFeeAccount,
            isSigner: false,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.tradeState,
            isSigner: false,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.tokenProgram ?? PublicKey.tokenProgramId,
            isSigner: false,
            isWritable: false
        )
    ]

    let ix = TransactionInstruction(
                keys: keys,
                programId: programId,
                data: data.0.bytes
            )
    return ix
}