/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita-swift
 */
import Foundation
import Beet
import Solana

/**
 * @category Instructions
 * @category CloseEscrowAccount
 * @category generated
 */
public struct CloseEscrowAccountInstructionArgs{
    let instructionDiscriminator: [UInt8] /* size: 8 */
    let escrowPaymentBump: UInt8

    public init(
        instructionDiscriminator: [UInt8] /* size: 8 */ = closeEscrowAccountInstructionDiscriminator,
        escrowPaymentBump: UInt8
    ) {
        self.instructionDiscriminator = instructionDiscriminator
        self.escrowPaymentBump = escrowPaymentBump
    }
}
/**
 * @category Instructions
 * @category CloseEscrowAccount
 * @category generated
 */
public let closeEscrowAccountStruct = FixableBeetArgsStruct<CloseEscrowAccountInstructionArgs>(
    fields: [
        ("instructionDiscriminator", Beet.fixedBeet(.init(value: .collection(UniformFixedSizeArray<UInt8>(element: .init(value: .scalar(u8())), len: 8))))),
        ("escrowPaymentBump", Beet.fixedBeet(.init(value: .scalar(u8()))))
    ],
    description: "CloseEscrowAccountInstructionArgs"
)
/**
* Accounts required by the _closeEscrowAccount_ instruction
*
* @property [**signer**] wallet  
* @property [_writable_] escrowPaymentAccount  
* @property [] auctionHouse   
* @category Instructions
* @category CloseEscrowAccount
* @category generated
*/
public struct CloseEscrowAccountInstructionAccounts {
    let wallet: PublicKey
    let escrowPaymentAccount: PublicKey
    let auctionHouse: PublicKey
    let systemProgram: PublicKey?

    public init(
        wallet: PublicKey,
        escrowPaymentAccount: PublicKey,
        auctionHouse: PublicKey,
        systemProgram: PublicKey? = nil
    ) {
        self.wallet = wallet
        self.escrowPaymentAccount = escrowPaymentAccount
        self.auctionHouse = auctionHouse
        self.systemProgram = systemProgram
    }
}

public let closeEscrowAccountInstructionDiscriminator = [209, 42, 208, 179, 140, 78, 18, 43] as [UInt8]

/**
* Creates a _CloseEscrowAccount_ instruction.
*
* @param accounts that will be accessed while the instruction is processed
  * @param args to provide as instruction data to the program
 * 
* @category Instructions
* @category CloseEscrowAccount
* @category generated
*/
public func createCloseEscrowAccountInstruction(accounts: CloseEscrowAccountInstructionAccounts, 
args: CloseEscrowAccountInstructionArgs, programId: PublicKey=PublicKey(string: "hausS13jsjafwWwGqZTUQRmWyvyxn9EQpqMwV1PBBmk")!) -> TransactionInstruction {

    let data = closeEscrowAccountStruct.serialize(
            instance: ["instructionDiscriminator": closeEscrowAccountInstructionDiscriminator,
"escrowPaymentBump": args.escrowPaymentBump])

    let keys: [AccountMeta] = [
        AccountMeta(
            publicKey: accounts.wallet,
            isSigner: true,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.escrowPaymentAccount,
            isSigner: false,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.auctionHouse,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.systemProgram ?? PublicKey.systemProgramId,
            isSigner: false,
            isWritable: false
        )
    ]

    let ix = TransactionInstruction(
                keys: keys,
                programId: programId,
                data: data.0.bytes
            )
    return ix
}