/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita-swift
 */
import Foundation
import Solana
import Beet

/**
 * @category Instructions
 * @category PrintListingReceipt
 * @category generated
 */
public struct PrintListingReceiptInstructionArgs{
    let instructionDiscriminator: [UInt8] /* size: 8 */
    let receiptBump: UInt8

    public init(
        instructionDiscriminator: [UInt8] /* size: 8 */ = printListingReceiptInstructionDiscriminator,
        receiptBump: UInt8
    ) {
        self.instructionDiscriminator = instructionDiscriminator
        self.receiptBump = receiptBump
    }
}
/**
 * @category Instructions
 * @category PrintListingReceipt
 * @category generated
 */
public let printListingReceiptStruct = FixableBeetArgsStruct<PrintListingReceiptInstructionArgs>(
    fields: [
        ("instructionDiscriminator", Beet.fixedBeet(.init(value: .collection(UniformFixedSizeArray<UInt8>(element: .init(value: .scalar(u8())), len: 8))))),
        ("receiptBump", Beet.fixedBeet(.init(value: .scalar(u8()))))
    ],
    description: "PrintListingReceiptInstructionArgs"
)
/**
* Accounts required by the _printListingReceipt_ instruction
*
* @property [_writable_] receipt  
* @property [_writable_, **signer**] bookkeeper  
* @property [] instruction   
* @category Instructions
* @category PrintListingReceipt
* @category generated
*/
public struct PrintListingReceiptInstructionAccounts {
    let receipt: PublicKey
    let bookkeeper: PublicKey
    let systemProgram: PublicKey?
    let rent: PublicKey?
    let instruction: PublicKey

    public init(
        receipt: PublicKey,
        bookkeeper: PublicKey,
        systemProgram: PublicKey? = nil,
        rent: PublicKey? = nil,
        instruction: PublicKey
    ) {
        self.receipt = receipt
        self.bookkeeper = bookkeeper
        self.systemProgram = systemProgram
        self.rent = rent
        self.instruction = instruction
    }
}

public let printListingReceiptInstructionDiscriminator = [207, 107, 44, 160, 75, 222, 195, 27] as [UInt8]

/**
* Creates a _PrintListingReceipt_ instruction.
*
* @param accounts that will be accessed while the instruction is processed
  * @param args to provide as instruction data to the program
 * 
* @category Instructions
* @category PrintListingReceipt
* @category generated
*/
public func createPrintListingReceiptInstruction(accounts: PrintListingReceiptInstructionAccounts, 
args: PrintListingReceiptInstructionArgs, programId: PublicKey=PublicKey(string: "hausS13jsjafwWwGqZTUQRmWyvyxn9EQpqMwV1PBBmk")!) -> TransactionInstruction {

    let data = printListingReceiptStruct.serialize(
            instance: ["instructionDiscriminator": printListingReceiptInstructionDiscriminator,
"receiptBump": args.receiptBump])

    let keys: [AccountMeta] = [
        AccountMeta(
            publicKey: accounts.receipt,
            isSigner: false,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.bookkeeper,
            isSigner: true,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.systemProgram ?? PublicKey.systemProgramId,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.rent ?? PublicKey.sysvarRent,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.instruction,
            isSigner: false,
            isWritable: false
        )
    ]

    let ix = TransactionInstruction(
                keys: keys,
                programId: programId,
                data: data.0.bytes
            )
    return ix
}