/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita-swift
 */
import Foundation
import Beet
import Solana

/**
 * @category Instructions
 * @category Withdraw
 * @category generated
 */
public struct WithdrawInstructionArgs{
    let instructionDiscriminator: [UInt8] /* size: 8 */
    let escrowPaymentBump: UInt8
    let amount: UInt64

    public init(
        instructionDiscriminator: [UInt8] /* size: 8 */ = withdrawInstructionDiscriminator,
        escrowPaymentBump: UInt8,
        amount: UInt64
    ) {
        self.instructionDiscriminator = instructionDiscriminator
        self.escrowPaymentBump = escrowPaymentBump
        self.amount = amount
    }
}
/**
 * @category Instructions
 * @category Withdraw
 * @category generated
 */
public let withdrawStruct = FixableBeetArgsStruct<WithdrawInstructionArgs>(
    fields: [
        ("instructionDiscriminator", Beet.fixedBeet(.init(value: .collection(UniformFixedSizeArray<UInt8>(element: .init(value: .scalar(u8())), len: 8))))),
        ("escrowPaymentBump", Beet.fixedBeet(.init(value: .scalar(u8())))),
        ("amount", Beet.fixedBeet(.init(value: .scalar(u64()))))
    ],
    description: "WithdrawInstructionArgs"
)
/**
* Accounts required by the _withdraw_ instruction
*
* @property [] wallet  
* @property [_writable_] receiptAccount  
* @property [_writable_] escrowPaymentAccount  
* @property [] treasuryMint  
* @property [] authority  
* @property [] auctionHouse  
* @property [_writable_] auctionHouseFeeAccount   
* @category Instructions
* @category Withdraw
* @category generated
*/
public struct WithdrawInstructionAccounts {
    let wallet: PublicKey
    let receiptAccount: PublicKey
    let escrowPaymentAccount: PublicKey
    let treasuryMint: PublicKey
    let authority: PublicKey
    let auctionHouse: PublicKey
    let auctionHouseFeeAccount: PublicKey
    let tokenProgram: PublicKey?
    let systemProgram: PublicKey?
    let ataProgram: PublicKey?
    let rent: PublicKey?

    public init(
        wallet: PublicKey,
        receiptAccount: PublicKey,
        escrowPaymentAccount: PublicKey,
        treasuryMint: PublicKey,
        authority: PublicKey,
        auctionHouse: PublicKey,
        auctionHouseFeeAccount: PublicKey,
        tokenProgram: PublicKey? = nil,
        systemProgram: PublicKey? = nil,
        ataProgram: PublicKey? = nil,
        rent: PublicKey? = nil
    ) {
        self.wallet = wallet
        self.receiptAccount = receiptAccount
        self.escrowPaymentAccount = escrowPaymentAccount
        self.treasuryMint = treasuryMint
        self.authority = authority
        self.auctionHouse = auctionHouse
        self.auctionHouseFeeAccount = auctionHouseFeeAccount
        self.tokenProgram = tokenProgram
        self.systemProgram = systemProgram
        self.ataProgram = ataProgram
        self.rent = rent
    }
}

public let withdrawInstructionDiscriminator = [183, 18, 70, 156, 148, 109, 161, 34] as [UInt8]

/**
* Creates a _Withdraw_ instruction.
*
* @param accounts that will be accessed while the instruction is processed
  * @param args to provide as instruction data to the program
 * 
* @category Instructions
* @category Withdraw
* @category generated
*/
public func createWithdrawInstruction(accounts: WithdrawInstructionAccounts, 
args: WithdrawInstructionArgs, programId: PublicKey=PublicKey(string: "hausS13jsjafwWwGqZTUQRmWyvyxn9EQpqMwV1PBBmk")!) -> TransactionInstruction {

    let data = withdrawStruct.serialize(
            instance: ["instructionDiscriminator": withdrawInstructionDiscriminator,
"escrowPaymentBump": args.escrowPaymentBump,
  "amount": args.amount])

    let keys: [AccountMeta] = [
        AccountMeta(
            publicKey: accounts.wallet,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.receiptAccount,
            isSigner: false,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.escrowPaymentAccount,
            isSigner: false,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.treasuryMint,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.authority,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.auctionHouse,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.auctionHouseFeeAccount,
            isSigner: false,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.tokenProgram ?? PublicKey.tokenProgramId,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.systemProgram ?? PublicKey.systemProgramId,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.ataProgram ?? PublicKey.splAssociatedTokenAccountProgramId,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.rent ?? PublicKey.sysvarRent,
            isSigner: false,
            isWritable: false
        )
    ]

    let ix = TransactionInstruction(
                keys: keys,
                programId: programId,
                data: data.0.bytes
            )
    return ix
}