/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita-swift
 */
import Foundation
import Beet
import Solana
import BeetSolana


/**
* Arguments used to create {@link Candyguard}
* @category Accounts
* @category generated
*/
public protocol CandyguardArgs {
    var candyGuardDiscriminator: [UInt8] { get }
     var base: PublicKey { get }
     var bump: UInt8 { get }
     var authority: PublicKey { get }
}

/**
 * Holds the data for the {@link Candyguard} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
public struct Candyguard: CandyguardArgs {
  public static let candyGuardDiscriminator = [44, 207, 199, 184, 112, 103, 34, 181] as [UInt8]

  public let candyGuardDiscriminator: [UInt8]
  public let base: PublicKey
  public let bump: UInt8
  public let authority: PublicKey

  /**
   * Creates a {@link Candyguard} instance from the provided args.
   */
  public static func fromArgs(args: Args) -> Candyguard {
    return Candyguard(
        candyGuardDiscriminator: args["accountDiscriminator"] as! [UInt8],
        base: args["base"] as! PublicKey,
        bump: args["bump"] as! UInt8,
        authority: args["authority"] as! PublicKey
    )
  }
  /**
   * Deserializes the {@link Candyguard} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  public static func fromAccountInfo(
    accountInfo: Foundation.Data,
    offset:Int=0
  ) -> ( Candyguard, Int )  {
    return Candyguard.deserialize(buf: accountInfo, offset: offset)
  }
  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link Candyguard} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  public static func fromAccountAddress(
    connection: Api,
    address: PublicKey,
    onComplete: @escaping (Result<Candyguard, Error>) -> Void
  ) {
    connection.getAccountInfo(account: address.base58EncodedString) { result in
        switch result {
            case .success(let pureData):
                if let data = pureData.data?.value {
                    onComplete(.success(Candyguard.deserialize(buf: data).0))
                } else {
                    onComplete(.failure(SolanaError.nullValue))
                }
            case .failure(let error):
                onComplete(.failure(error))
        }
    }
  }
  /**
   * Deserializes the {@link Candyguard} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  public static func deserialize(
    buf: Foundation.Data,
    offset: Int = 0
  ) -> ( Candyguard, Int ) {
    return candyGuardBeet.deserialize(buffer: buf, offset: offset)
  }
  /**
   * Serializes the {@link Candyguard} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  public func serialize() -> ( Foundation.Data, Int ) {
    return candyGuardBeet.serialize(instance: Candyguard(candyGuardDiscriminator : self.candyGuardDiscriminator,
        base : self.base,
        bump : self.bump,
        authority : self.authority))
  }
    /**
  * Returns the byteSize of a {@link Buffer} holding the serialized data of
  * {@link Candyguard}
  */
  static func byteSize() -> UInt {
      return candyGuardBeet.byteSize
  }
  /**
  * Fetches the minimum balance needed to exempt an account holding
  * {@link Candyguard} data from rent
  *
  * @param connection used to retrieve the rent exemption information
  */
  static func getMinimumBalanceForRentExemption(
      connection: Api,
      commitment: Commitment?,
      onComplete: @escaping(Result<UInt64, Error>) -> Void
  ) {
      return connection.getMinimumBalanceForRentExemption(dataLength: UInt64(Candyguard.byteSize()), commitment: commitment, onComplete: onComplete)
  }
  /**
  * Determines if the provided {@link Buffer} has the correct byte size to
  * hold {@link Candyguard} data.
  */
  static func hasCorrectByteSize(buf: Foundation.Data, offset:Int=0) -> Bool {
      return buf.bytes.count - offset == Candyguard.byteSize()
  }
}
  /**
   * @category Accounts
   * @category generated
   */
  public let candyGuardBeet = BeetStruct(
    fields:[
        ("accountDiscriminator", (.init(value: .collection(UniformFixedSizeArray<UInt8>(element: .init(value: .scalar(u8())), len: 8))))),
        ("base", (.init(value: .scalar(BeetPublicKey())))),
        ("bump", (.init(value: .scalar(u8())))),
        ("authority", (.init(value: .scalar(BeetPublicKey()))))
    ],
    construct: Candyguard.fromArgs,
    description: "Candyguard"
)
