/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita-swift
 */
import Foundation
import Solana
import Beet

/**
 * @category Instructions
 * @category CreateMasterEditionV3
 * @category generated
 */
public struct CreateMasterEditionV3InstructionArgs{
    let instructionDiscriminator: [UInt8] /* size: 8 */
    let createMasterEditionArgs: CreateMasterEditionArgs

    public init(
        instructionDiscriminator: [UInt8] /* size: 8 */ = createMasterEditionV3InstructionDiscriminator,
        createMasterEditionArgs: CreateMasterEditionArgs
    ) {
        self.instructionDiscriminator = instructionDiscriminator
        self.createMasterEditionArgs = createMasterEditionArgs
    }
}
/**
 * @category Instructions
 * @category CreateMasterEditionV3
 * @category generated
 */
public let CreateMasterEditionV3Struct = FixableBeetArgsStruct<CreateMasterEditionV3InstructionArgs>(
    fields: [
        ("instructionDiscriminator", Beet.fixedBeet(.init(value: .collection(UniformFixedSizeArray<UInt8>(element: .init(value: .scalar(u8())), len: 8))))),
        ("createMasterEditionArgs", createMasterEditionArgsBeetWrapped)
    ],
    description: "CreateMasterEditionV3InstructionArgs"
)
/**
* Accounts required by the _CreateMasterEditionV3_ instruction
*
* @property [_writable_] edition  
* @property [_writable_] mint  
* @property [**signer**] updateAuthority  
* @property [**signer**] mintAuthority  
* @property [_writable_, **signer**] payer  
* @property [_writable_] metadata   
* @category Instructions
* @category CreateMasterEditionV3
* @category generated
*/
public struct CreateMasterEditionV3InstructionAccounts {
    let edition: PublicKey
    let mint: PublicKey
    let updateAuthority: PublicKey
    let mintAuthority: PublicKey
    let payer: PublicKey
    let metadata: PublicKey
    let tokenProgram: PublicKey?
    let systemProgram: PublicKey?
    let rent: PublicKey?

    public init(
        edition: PublicKey,
        mint: PublicKey,
        updateAuthority: PublicKey,
        mintAuthority: PublicKey,
        payer: PublicKey,
        metadata: PublicKey,
        tokenProgram: PublicKey? = nil,
        systemProgram: PublicKey? = nil,
        rent: PublicKey? = nil
    ) {
        self.edition = edition
        self.mint = mint
        self.updateAuthority = updateAuthority
        self.mintAuthority = mintAuthority
        self.payer = payer
        self.metadata = metadata
        self.tokenProgram = tokenProgram
        self.systemProgram = systemProgram
        self.rent = rent
    }
}

public let createMasterEditionV3InstructionDiscriminator = [147, 149, 17, 159, 74, 134, 114, 237] as [UInt8]

/**
* Creates a _CreateMasterEditionV3_ instruction.
*
* @param accounts that will be accessed while the instruction is processed
  * @param args to provide as instruction data to the program
 * 
* @category Instructions
* @category CreateMasterEditionV3
* @category generated
*/
public func createCreateMasterEditionV3Instruction(accounts: CreateMasterEditionV3InstructionAccounts, 
args: CreateMasterEditionV3InstructionArgs, programId: PublicKey=PublicKey(string: "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s")!) -> TransactionInstruction {

    let data = CreateMasterEditionV3Struct.serialize(
            instance: ["instructionDiscriminator": createMasterEditionV3InstructionDiscriminator,
"createMasterEditionArgs": args.createMasterEditionArgs])

    var keys: [AccountMeta] = [
        AccountMeta(
            publicKey: accounts.edition,
            isSigner: false,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.mint,
            isSigner: false,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.updateAuthority,
            isSigner: true,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.mintAuthority,
            isSigner: true,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.payer,
            isSigner: true,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.metadata,
            isSigner: false,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.tokenProgram ?? PublicKey.tokenProgramId,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.systemProgram ?? PublicKey.systemProgramId,
            isSigner: false,
            isWritable: false
        )
    ]
    if accounts.rent != nil {
        
        keys.append(
            AccountMeta(
                publicKey: accounts.rent!,
                isSigner: false,
                isWritable: false
            )
        )
    } 

    let ix = TransactionInstruction(
                keys: keys,
                programId: programId,
                data: data.0.bytes
            )
    return ix
}