/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita-swift
 */
import Foundation
import Beet
import Solana

/**
 * @category Instructions
 * @category CreateMasterEdition
 * @category generated
 */
public struct CreateMasterEditionInstructionArgs{
    let instructionDiscriminator: [UInt8] /* size: 8 */
    let createMasterEditionArgs: CreateMasterEditionArgs

    public init(
        instructionDiscriminator: [UInt8] /* size: 8 */ = createMasterEditionInstructionDiscriminator,
        createMasterEditionArgs: CreateMasterEditionArgs
    ) {
        self.instructionDiscriminator = instructionDiscriminator
        self.createMasterEditionArgs = createMasterEditionArgs
    }
}
/**
 * @category Instructions
 * @category CreateMasterEdition
 * @category generated
 */
public let CreateMasterEditionStruct = FixableBeetArgsStruct<CreateMasterEditionInstructionArgs>(
    fields: [
        ("instructionDiscriminator", Beet.fixedBeet(.init(value: .collection(UniformFixedSizeArray<UInt8>(element: .init(value: .scalar(u8())), len: 8))))),
        ("createMasterEditionArgs", createMasterEditionArgsBeetWrapped)
    ],
    description: "CreateMasterEditionInstructionArgs"
)
/**
* Accounts required by the _CreateMasterEdition_ instruction
*
* @property [_writable_] edition  
* @property [_writable_] mint  
* @property [**signer**] updateAuthority  
* @property [**signer**] mintAuthority  
* @property [_writable_, **signer**] payer  
* @property [] metadata   
* @category Instructions
* @category CreateMasterEdition
* @category generated
*/
public struct CreateMasterEditionInstructionAccounts {
    let edition: PublicKey
    let mint: PublicKey
    let updateAuthority: PublicKey
    let mintAuthority: PublicKey
    let payer: PublicKey
    let metadata: PublicKey
    let tokenProgram: PublicKey?
    let systemProgram: PublicKey?
    let rent: PublicKey?

    public init(
        edition: PublicKey,
        mint: PublicKey,
        updateAuthority: PublicKey,
        mintAuthority: PublicKey,
        payer: PublicKey,
        metadata: PublicKey,
        tokenProgram: PublicKey? = nil,
        systemProgram: PublicKey? = nil,
        rent: PublicKey? = nil
    ) {
        self.edition = edition
        self.mint = mint
        self.updateAuthority = updateAuthority
        self.mintAuthority = mintAuthority
        self.payer = payer
        self.metadata = metadata
        self.tokenProgram = tokenProgram
        self.systemProgram = systemProgram
        self.rent = rent
    }
}

public let createMasterEditionInstructionDiscriminator = [179, 210, 96, 96, 57, 25, 79, 69] as [UInt8]

/**
* Creates a _CreateMasterEdition_ instruction.
*
* @param accounts that will be accessed while the instruction is processed
  * @param args to provide as instruction data to the program
 * 
* @category Instructions
* @category CreateMasterEdition
* @category generated
*/
public func createCreateMasterEditionInstruction(accounts: CreateMasterEditionInstructionAccounts, 
args: CreateMasterEditionInstructionArgs, programId: PublicKey=PublicKey(string: "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s")!) -> TransactionInstruction {

    let data = CreateMasterEditionStruct.serialize(
            instance: ["instructionDiscriminator": createMasterEditionInstructionDiscriminator,
"createMasterEditionArgs": args.createMasterEditionArgs])

    let keys: [AccountMeta] = [
        AccountMeta(
            publicKey: accounts.edition,
            isSigner: false,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.mint,
            isSigner: false,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.updateAuthority,
            isSigner: true,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.mintAuthority,
            isSigner: true,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.payer,
            isSigner: true,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.metadata,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.tokenProgram ?? PublicKey.tokenProgramId,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.systemProgram ?? PublicKey.systemProgramId,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.rent ?? PublicKey.sysvarRent,
            isSigner: false,
            isWritable: false
        )
    ]

    let ix = TransactionInstruction(
                keys: keys,
                programId: programId,
                data: data.0.bytes
            )
    return ix
}