/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita-swift
 */
import Foundation
import Beet
import Solana

/**
 * @category Instructions
 * @category Lock
 * @category generated
 */
public struct LockInstructionArgs{
    let instructionDiscriminator: [UInt8] /* size: 8 */
    let lockArgs: LockArgs

    public init(
        instructionDiscriminator: [UInt8] /* size: 8 */ = lockInstructionDiscriminator,
        lockArgs: LockArgs
    ) {
        self.instructionDiscriminator = instructionDiscriminator
        self.lockArgs = lockArgs
    }
}
/**
 * @category Instructions
 * @category Lock
 * @category generated
 */
public let LockStruct = FixableBeetArgsStruct<LockInstructionArgs>(
    fields: [
        ("instructionDiscriminator", Beet.fixedBeet(.init(value: .collection(UniformFixedSizeArray<UInt8>(element: .init(value: .scalar(u8())), len: 8))))),
        ("lockArgs", lockArgsBeetWrapped)
    ],
    description: "LockInstructionArgs"
)
/**
* Accounts required by the _Lock_ instruction
*
* @property [**signer**] authority  
* @property [] tokenOwner (optional)  
* @property [_writable_] token  
* @property [] mint  
* @property [_writable_] metadata  
* @property [] edition (optional)  
* @property [_writable_] tokenRecord (optional)  
* @property [_writable_, **signer**] payer  
* @property [] sysvarInstructions  
* @property [] splTokenProgram (optional)  
* @property [] authorizationRulesProgram (optional)  
* @property [] authorizationRules (optional)   
* @category Instructions
* @category Lock
* @category generated
*/
public struct LockInstructionAccounts {
    let authority: PublicKey
    let tokenOwner: PublicKey?
    let token: PublicKey
    let mint: PublicKey
    let metadata: PublicKey
    let edition: PublicKey?
    let tokenRecord: PublicKey?
    let payer: PublicKey
    let systemProgram: PublicKey?
    let sysvarInstructions: PublicKey
    let splTokenProgram: PublicKey?
    let authorizationRulesProgram: PublicKey?
    let authorizationRules: PublicKey?

    public init(
        authority: PublicKey,
        tokenOwner: PublicKey? = nil,
        token: PublicKey,
        mint: PublicKey,
        metadata: PublicKey,
        edition: PublicKey? = nil,
        tokenRecord: PublicKey? = nil,
        payer: PublicKey,
        systemProgram: PublicKey? = nil,
        sysvarInstructions: PublicKey,
        splTokenProgram: PublicKey? = nil,
        authorizationRulesProgram: PublicKey? = nil,
        authorizationRules: PublicKey? = nil
    ) {
        self.authority = authority
        self.tokenOwner = tokenOwner
        self.token = token
        self.mint = mint
        self.metadata = metadata
        self.edition = edition
        self.tokenRecord = tokenRecord
        self.payer = payer
        self.systemProgram = systemProgram
        self.sysvarInstructions = sysvarInstructions
        self.splTokenProgram = splTokenProgram
        self.authorizationRulesProgram = authorizationRulesProgram
        self.authorizationRules = authorizationRules
    }
}

public let lockInstructionDiscriminator = [21, 19, 208, 43, 237, 62, 255, 87] as [UInt8]

/**
* Creates a _Lock_ instruction.
*
* @param accounts that will be accessed while the instruction is processed
  * @param args to provide as instruction data to the program
 * 
* @category Instructions
* @category Lock
* @category generated
*/
public func createLockInstruction(accounts: LockInstructionAccounts, 
args: LockInstructionArgs, programId: PublicKey=PublicKey(string: "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s")!) -> TransactionInstruction {

    let data = LockStruct.serialize(
            instance: ["instructionDiscriminator": lockInstructionDiscriminator,
"lockArgs": args.lockArgs])

    var keys: [AccountMeta] = [
        AccountMeta(
            publicKey: accounts.authority,
            isSigner: true,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.token,
            isSigner: false,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.mint,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.metadata,
            isSigner: false,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.payer,
            isSigner: true,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.systemProgram ?? PublicKey.systemProgramId,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.sysvarInstructions,
            isSigner: false,
            isWritable: false
        )
    ]
    if accounts.tokenOwner != nil {
        
        keys.append(
            AccountMeta(
                publicKey: accounts.tokenOwner!,
                isSigner: false,
                isWritable: false
            )
        )
    }  else {
        keys.append(
            AccountMeta(
                publicKey: programId,
                isSigner: false,
                isWritable: false
            )
        )
    }
    if accounts.edition != nil {
        if accounts.tokenOwner == nil { fatalError("When providing edition accounts.tokenOwner need(s) to be provided as well.") }
        keys.append(
            AccountMeta(
                publicKey: accounts.edition!,
                isSigner: false,
                isWritable: false
            )
        )
    }  else {
        keys.append(
            AccountMeta(
                publicKey: programId,
                isSigner: false,
                isWritable: false
            )
        )
    }
    if accounts.tokenRecord != nil {
        if accounts.tokenOwner == nil || accounts.edition == nil { fatalError("When providing tokenRecord accounts.tokenOwner, accounts.edition need(s) to be provided as well.") }
        keys.append(
            AccountMeta(
                publicKey: accounts.tokenRecord!,
                isSigner: false,
                isWritable: true
            )
        )
    }  else {
        keys.append(
            AccountMeta(
                publicKey: programId,
                isSigner: false,
                isWritable: false
            )
        )
    }
    if accounts.splTokenProgram != nil {
        if accounts.tokenOwner == nil || accounts.edition == nil || accounts.tokenRecord == nil { fatalError("When providing splTokenProgram accounts.tokenOwner, accounts.edition, accounts.tokenRecord need(s) to be provided as well.") }
        keys.append(
            AccountMeta(
                publicKey: accounts.splTokenProgram!,
                isSigner: false,
                isWritable: false
            )
        )
    }  else {
        keys.append(
            AccountMeta(
                publicKey: programId,
                isSigner: false,
                isWritable: false
            )
        )
    }
    if accounts.authorizationRulesProgram != nil {
        if accounts.tokenOwner == nil || accounts.edition == nil || accounts.tokenRecord == nil || accounts.splTokenProgram == nil { fatalError("When providing authorizationRulesProgram accounts.tokenOwner, accounts.edition, accounts.tokenRecord, accounts.splTokenProgram need(s) to be provided as well.") }
        keys.append(
            AccountMeta(
                publicKey: accounts.authorizationRulesProgram!,
                isSigner: false,
                isWritable: false
            )
        )
    }  else {
        keys.append(
            AccountMeta(
                publicKey: programId,
                isSigner: false,
                isWritable: false
            )
        )
    }
    if accounts.authorizationRules != nil {
        if accounts.tokenOwner == nil || accounts.edition == nil || accounts.tokenRecord == nil || accounts.splTokenProgram == nil || accounts.authorizationRulesProgram == nil { fatalError("When providing authorizationRules accounts.tokenOwner, accounts.edition, accounts.tokenRecord, accounts.splTokenProgram, accounts.authorizationRulesProgram need(s) to be provided as well.") }
        keys.append(
            AccountMeta(
                publicKey: accounts.authorizationRules!,
                isSigner: false,
                isWritable: false
            )
        )
    }  else {
        keys.append(
            AccountMeta(
                publicKey: programId,
                isSigner: false,
                isWritable: false
            )
        )
    }

    let ix = TransactionInstruction(
                keys: keys,
                programId: programId,
                data: data.0.bytes
            )
    return ix
}