/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita-swift
 */
import Foundation
import Beet
import Solana

/**
 * @category Instructions
 * @category Migrate
 * @category generated
 */
public struct MigrateInstructionArgs{
    let instructionDiscriminator: [UInt8] /* size: 8 */
    let migrateArgs: MigrateArgs

    public init(
        instructionDiscriminator: [UInt8] /* size: 8 */ = migrateInstructionDiscriminator,
        migrateArgs: MigrateArgs
    ) {
        self.instructionDiscriminator = instructionDiscriminator
        self.migrateArgs = migrateArgs
    }
}
/**
 * @category Instructions
 * @category Migrate
 * @category generated
 */
public let MigrateStruct = FixableBeetArgsStruct<MigrateInstructionArgs>(
    fields: [
        ("instructionDiscriminator", Beet.fixedBeet(.init(value: .collection(UniformFixedSizeArray<UInt8>(element: .init(value: .scalar(u8())), len: 8))))),
        ("migrateArgs", migrateArgsBeetWrapped)
    ],
    description: "MigrateInstructionArgs"
)
/**
* Accounts required by the _Migrate_ instruction
*
* @property [_writable_] metadata  
* @property [_writable_] edition  
* @property [_writable_] token  
* @property [] tokenOwner  
* @property [] mint  
* @property [_writable_, **signer**] payer  
* @property [**signer**] authority  
* @property [] collectionMetadata  
* @property [] delegateRecord  
* @property [] tokenRecord  
* @property [] sysvarInstructions  
* @property [] splTokenProgram  
* @property [] authorizationRulesProgram (optional)  
* @property [] authorizationRules (optional)   
* @category Instructions
* @category Migrate
* @category generated
*/
public struct MigrateInstructionAccounts {
    let metadata: PublicKey
    let edition: PublicKey
    let token: PublicKey
    let tokenOwner: PublicKey
    let mint: PublicKey
    let payer: PublicKey
    let authority: PublicKey
    let collectionMetadata: PublicKey
    let delegateRecord: PublicKey
    let tokenRecord: PublicKey
    let systemProgram: PublicKey?
    let sysvarInstructions: PublicKey
    let splTokenProgram: PublicKey
    let authorizationRulesProgram: PublicKey?
    let authorizationRules: PublicKey?

    public init(
        metadata: PublicKey,
        edition: PublicKey,
        token: PublicKey,
        tokenOwner: PublicKey,
        mint: PublicKey,
        payer: PublicKey,
        authority: PublicKey,
        collectionMetadata: PublicKey,
        delegateRecord: PublicKey,
        tokenRecord: PublicKey,
        systemProgram: PublicKey? = nil,
        sysvarInstructions: PublicKey,
        splTokenProgram: PublicKey,
        authorizationRulesProgram: PublicKey? = nil,
        authorizationRules: PublicKey? = nil
    ) {
        self.metadata = metadata
        self.edition = edition
        self.token = token
        self.tokenOwner = tokenOwner
        self.mint = mint
        self.payer = payer
        self.authority = authority
        self.collectionMetadata = collectionMetadata
        self.delegateRecord = delegateRecord
        self.tokenRecord = tokenRecord
        self.systemProgram = systemProgram
        self.sysvarInstructions = sysvarInstructions
        self.splTokenProgram = splTokenProgram
        self.authorizationRulesProgram = authorizationRulesProgram
        self.authorizationRules = authorizationRules
    }
}

public let migrateInstructionDiscriminator = [155, 234, 231, 146, 236, 158, 162, 30] as [UInt8]

/**
* Creates a _Migrate_ instruction.
*
* @param accounts that will be accessed while the instruction is processed
  * @param args to provide as instruction data to the program
 * 
* @category Instructions
* @category Migrate
* @category generated
*/
public func createMigrateInstruction(accounts: MigrateInstructionAccounts, 
args: MigrateInstructionArgs, programId: PublicKey=PublicKey(string: "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s")!) -> TransactionInstruction {

    let data = MigrateStruct.serialize(
            instance: ["instructionDiscriminator": migrateInstructionDiscriminator,
"migrateArgs": args.migrateArgs])

    var keys: [AccountMeta] = [
        AccountMeta(
            publicKey: accounts.metadata,
            isSigner: false,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.edition,
            isSigner: false,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.token,
            isSigner: false,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.tokenOwner,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.mint,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.payer,
            isSigner: true,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.authority,
            isSigner: true,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.collectionMetadata,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.delegateRecord,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.tokenRecord,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.systemProgram ?? PublicKey.systemProgramId,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.sysvarInstructions,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.splTokenProgram,
            isSigner: false,
            isWritable: false
        )
    ]
    if accounts.authorizationRulesProgram != nil {
        
        keys.append(
            AccountMeta(
                publicKey: accounts.authorizationRulesProgram!,
                isSigner: false,
                isWritable: false
            )
        )
    }  else {
        keys.append(
            AccountMeta(
                publicKey: programId,
                isSigner: false,
                isWritable: false
            )
        )
    }
    if accounts.authorizationRules != nil {
        if accounts.authorizationRulesProgram == nil { fatalError("When providing authorizationRules accounts.authorizationRulesProgram need(s) to be provided as well.") }
        keys.append(
            AccountMeta(
                publicKey: accounts.authorizationRules!,
                isSigner: false,
                isWritable: false
            )
        )
    }  else {
        keys.append(
            AccountMeta(
                publicKey: programId,
                isSigner: false,
                isWritable: false
            )
        )
    }

    let ix = TransactionInstruction(
                keys: keys,
                programId: programId,
                data: data.0.bytes
            )
    return ix
}