/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita-swift
 */
import Foundation
import Beet
import Solana

/**
 * @category Instructions
 * @category RemoveCreatorVerification
 * @category generated
 */
public struct RemoveCreatorVerificationInstructionArgs{
    let instructionDiscriminator: [UInt8] /* size: 8 */
    

    public init(
        instructionDiscriminator: [UInt8] /* size: 8 */ = removeCreatorVerificationInstructionDiscriminator
    ) {
        self.instructionDiscriminator = instructionDiscriminator
    }
}
/**
 * @category Instructions
 * @category RemoveCreatorVerification
 * @category generated
 */
public let RemoveCreatorVerificationStruct = FixableBeetArgsStruct<RemoveCreatorVerificationInstructionArgs>(
    fields: [
        ("instructionDiscriminator", Beet.fixedBeet(.init(value: .collection(UniformFixedSizeArray<UInt8>(element: .init(value: .scalar(u8())), len: 8))))),
        
    ],
    description: "RemoveCreatorVerificationInstructionArgs"
)
/**
* Accounts required by the _RemoveCreatorVerification_ instruction
*
* @property [_writable_] metadata  
* @property [**signer**] creator   
* @category Instructions
* @category RemoveCreatorVerification
* @category generated
*/
public struct RemoveCreatorVerificationInstructionAccounts {
    let metadata: PublicKey
    let creator: PublicKey

    public init(
        metadata: PublicKey,
        creator: PublicKey
    ) {
        self.metadata = metadata
        self.creator = creator
    }
}

public let removeCreatorVerificationInstructionDiscriminator = [41, 194, 140, 217, 90, 160, 139, 6] as [UInt8]

/**
* Creates a _RemoveCreatorVerification_ instruction.
*
* @param accounts that will be accessed while the instruction is processed
* @category Instructions
* @category RemoveCreatorVerification
* @category generated
*/
public func createRemoveCreatorVerificationInstruction(accounts: RemoveCreatorVerificationInstructionAccounts, 
programId: PublicKey=PublicKey(string: "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s")!) -> TransactionInstruction {

    let data = RemoveCreatorVerificationStruct.serialize(
            instance: ["instructionDiscriminator": removeCreatorVerificationInstructionDiscriminator ])

    let keys: [AccountMeta] = [
        AccountMeta(
            publicKey: accounts.metadata,
            isSigner: false,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.creator,
            isSigner: true,
            isWritable: false
        )
    ]

    let ix = TransactionInstruction(
                keys: keys,
                programId: programId,
                data: data.0.bytes
            )
    return ix
}