/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita-swift
 */
import Foundation
import Beet
import Solana

/**
 * @category Instructions
 * @category Revoke
 * @category generated
 */
public struct RevokeInstructionArgs{
    let instructionDiscriminator: [UInt8] /* size: 8 */
    let revokeArgs: RevokeArgs

    public init(
        instructionDiscriminator: [UInt8] /* size: 8 */ = revokeInstructionDiscriminator,
        revokeArgs: RevokeArgs
    ) {
        self.instructionDiscriminator = instructionDiscriminator
        self.revokeArgs = revokeArgs
    }
}
/**
 * @category Instructions
 * @category Revoke
 * @category generated
 */
public let RevokeStruct = FixableBeetArgsStruct<RevokeInstructionArgs>(
    fields: [
        ("instructionDiscriminator", Beet.fixedBeet(.init(value: .collection(UniformFixedSizeArray<UInt8>(element: .init(value: .scalar(u8())), len: 8))))),
        ("revokeArgs", revokeArgsBeetWrapped)
    ],
    description: "RevokeInstructionArgs"
)
/**
* Accounts required by the _Revoke_ instruction
*
* @property [_writable_] delegateRecord (optional)  
* @property [] delegate  
* @property [_writable_] metadata  
* @property [] masterEdition (optional)  
* @property [_writable_] tokenRecord (optional)  
* @property [] mint  
* @property [_writable_] token (optional)  
* @property [**signer**] authority  
* @property [_writable_, **signer**] payer  
* @property [] sysvarInstructions  
* @property [] splTokenProgram (optional)  
* @property [] authorizationRulesProgram (optional)  
* @property [] authorizationRules (optional)   
* @category Instructions
* @category Revoke
* @category generated
*/
public struct RevokeInstructionAccounts {
    let delegateRecord: PublicKey?
    let delegate: PublicKey
    let metadata: PublicKey
    let masterEdition: PublicKey?
    let tokenRecord: PublicKey?
    let mint: PublicKey
    let token: PublicKey?
    let authority: PublicKey
    let payer: PublicKey
    let systemProgram: PublicKey?
    let sysvarInstructions: PublicKey
    let splTokenProgram: PublicKey?
    let authorizationRulesProgram: PublicKey?
    let authorizationRules: PublicKey?

    public init(
        delegateRecord: PublicKey? = nil,
        delegate: PublicKey,
        metadata: PublicKey,
        masterEdition: PublicKey? = nil,
        tokenRecord: PublicKey? = nil,
        mint: PublicKey,
        token: PublicKey? = nil,
        authority: PublicKey,
        payer: PublicKey,
        systemProgram: PublicKey? = nil,
        sysvarInstructions: PublicKey,
        splTokenProgram: PublicKey? = nil,
        authorizationRulesProgram: PublicKey? = nil,
        authorizationRules: PublicKey? = nil
    ) {
        self.delegateRecord = delegateRecord
        self.delegate = delegate
        self.metadata = metadata
        self.masterEdition = masterEdition
        self.tokenRecord = tokenRecord
        self.mint = mint
        self.token = token
        self.authority = authority
        self.payer = payer
        self.systemProgram = systemProgram
        self.sysvarInstructions = sysvarInstructions
        self.splTokenProgram = splTokenProgram
        self.authorizationRulesProgram = authorizationRulesProgram
        self.authorizationRules = authorizationRules
    }
}

public let revokeInstructionDiscriminator = [170, 23, 31, 34, 133, 173, 93, 242] as [UInt8]

/**
* Creates a _Revoke_ instruction.
*
* @param accounts that will be accessed while the instruction is processed
  * @param args to provide as instruction data to the program
 * 
* @category Instructions
* @category Revoke
* @category generated
*/
public func createRevokeInstruction(accounts: RevokeInstructionAccounts, 
args: RevokeInstructionArgs, programId: PublicKey=PublicKey(string: "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s")!) -> TransactionInstruction {

    let data = RevokeStruct.serialize(
            instance: ["instructionDiscriminator": revokeInstructionDiscriminator,
"revokeArgs": args.revokeArgs])

    var keys: [AccountMeta] = [
        AccountMeta(
            publicKey: accounts.delegate,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.metadata,
            isSigner: false,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.mint,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.authority,
            isSigner: true,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.payer,
            isSigner: true,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.systemProgram ?? PublicKey.systemProgramId,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.sysvarInstructions,
            isSigner: false,
            isWritable: false
        )
    ]
    if accounts.delegateRecord != nil {
        
        keys.append(
            AccountMeta(
                publicKey: accounts.delegateRecord!,
                isSigner: false,
                isWritable: true
            )
        )
    }  else {
        keys.append(
            AccountMeta(
                publicKey: programId,
                isSigner: false,
                isWritable: false
            )
        )
    }
    if accounts.masterEdition != nil {
        if accounts.delegateRecord == nil { fatalError("When providing masterEdition accounts.delegateRecord need(s) to be provided as well.") }
        keys.append(
            AccountMeta(
                publicKey: accounts.masterEdition!,
                isSigner: false,
                isWritable: false
            )
        )
    }  else {
        keys.append(
            AccountMeta(
                publicKey: programId,
                isSigner: false,
                isWritable: false
            )
        )
    }
    if accounts.tokenRecord != nil {
        if accounts.delegateRecord == nil || accounts.masterEdition == nil { fatalError("When providing tokenRecord accounts.delegateRecord, accounts.masterEdition need(s) to be provided as well.") }
        keys.append(
            AccountMeta(
                publicKey: accounts.tokenRecord!,
                isSigner: false,
                isWritable: true
            )
        )
    }  else {
        keys.append(
            AccountMeta(
                publicKey: programId,
                isSigner: false,
                isWritable: false
            )
        )
    }
    if accounts.token != nil {
        if accounts.delegateRecord == nil || accounts.masterEdition == nil || accounts.tokenRecord == nil { fatalError("When providing token accounts.delegateRecord, accounts.masterEdition, accounts.tokenRecord need(s) to be provided as well.") }
        keys.append(
            AccountMeta(
                publicKey: accounts.token!,
                isSigner: false,
                isWritable: true
            )
        )
    }  else {
        keys.append(
            AccountMeta(
                publicKey: programId,
                isSigner: false,
                isWritable: false
            )
        )
    }
    if accounts.splTokenProgram != nil {
        if accounts.delegateRecord == nil || accounts.masterEdition == nil || accounts.tokenRecord == nil || accounts.token == nil { fatalError("When providing splTokenProgram accounts.delegateRecord, accounts.masterEdition, accounts.tokenRecord, accounts.token need(s) to be provided as well.") }
        keys.append(
            AccountMeta(
                publicKey: accounts.splTokenProgram!,
                isSigner: false,
                isWritable: false
            )
        )
    }  else {
        keys.append(
            AccountMeta(
                publicKey: programId,
                isSigner: false,
                isWritable: false
            )
        )
    }
    if accounts.authorizationRulesProgram != nil {
        if accounts.delegateRecord == nil || accounts.masterEdition == nil || accounts.tokenRecord == nil || accounts.token == nil || accounts.splTokenProgram == nil { fatalError("When providing authorizationRulesProgram accounts.delegateRecord, accounts.masterEdition, accounts.tokenRecord, accounts.token, accounts.splTokenProgram need(s) to be provided as well.") }
        keys.append(
            AccountMeta(
                publicKey: accounts.authorizationRulesProgram!,
                isSigner: false,
                isWritable: false
            )
        )
    }  else {
        keys.append(
            AccountMeta(
                publicKey: programId,
                isSigner: false,
                isWritable: false
            )
        )
    }
    if accounts.authorizationRules != nil {
        if accounts.delegateRecord == nil || accounts.masterEdition == nil || accounts.tokenRecord == nil || accounts.token == nil || accounts.splTokenProgram == nil || accounts.authorizationRulesProgram == nil { fatalError("When providing authorizationRules accounts.delegateRecord, accounts.masterEdition, accounts.tokenRecord, accounts.token, accounts.splTokenProgram, accounts.authorizationRulesProgram need(s) to be provided as well.") }
        keys.append(
            AccountMeta(
                publicKey: accounts.authorizationRules!,
                isSigner: false,
                isWritable: false
            )
        )
    }  else {
        keys.append(
            AccountMeta(
                publicKey: programId,
                isSigner: false,
                isWritable: false
            )
        )
    }

    let ix = TransactionInstruction(
                keys: keys,
                programId: programId,
                data: data.0.bytes
            )
    return ix
}