/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita-swift
 */
import Foundation
import Solana
import Beet

/**
 * @category Instructions
 * @category SetAndVerifyCollection
 * @category generated
 */
public struct SetAndVerifyCollectionInstructionArgs{
    let instructionDiscriminator: [UInt8] /* size: 8 */
    

    public init(
        instructionDiscriminator: [UInt8] /* size: 8 */ = setAndVerifyCollectionInstructionDiscriminator
    ) {
        self.instructionDiscriminator = instructionDiscriminator
    }
}
/**
 * @category Instructions
 * @category SetAndVerifyCollection
 * @category generated
 */
public let SetAndVerifyCollectionStruct = FixableBeetArgsStruct<SetAndVerifyCollectionInstructionArgs>(
    fields: [
        ("instructionDiscriminator", Beet.fixedBeet(.init(value: .collection(UniformFixedSizeArray<UInt8>(element: .init(value: .scalar(u8())), len: 8))))),
        
    ],
    description: "SetAndVerifyCollectionInstructionArgs"
)
/**
* Accounts required by the _SetAndVerifyCollection_ instruction
*
* @property [_writable_] metadata  
* @property [_writable_, **signer**] collectionAuthority  
* @property [_writable_, **signer**] payer  
* @property [] updateAuthority  
* @property [] collectionMint  
* @property [] collection  
* @property [] collectionMasterEditionAccount  
* @property [] collectionAuthorityRecord (optional)   
* @category Instructions
* @category SetAndVerifyCollection
* @category generated
*/
public struct SetAndVerifyCollectionInstructionAccounts {
    let metadata: PublicKey
    let collectionAuthority: PublicKey
    let payer: PublicKey
    let updateAuthority: PublicKey
    let collectionMint: PublicKey
    let collection: PublicKey
    let collectionMasterEditionAccount: PublicKey
    let collectionAuthorityRecord: PublicKey?

    public init(
        metadata: PublicKey,
        collectionAuthority: PublicKey,
        payer: PublicKey,
        updateAuthority: PublicKey,
        collectionMint: PublicKey,
        collection: PublicKey,
        collectionMasterEditionAccount: PublicKey,
        collectionAuthorityRecord: PublicKey? = nil
    ) {
        self.metadata = metadata
        self.collectionAuthority = collectionAuthority
        self.payer = payer
        self.updateAuthority = updateAuthority
        self.collectionMint = collectionMint
        self.collection = collection
        self.collectionMasterEditionAccount = collectionMasterEditionAccount
        self.collectionAuthorityRecord = collectionAuthorityRecord
    }
}

public let setAndVerifyCollectionInstructionDiscriminator = [235, 242, 121, 216, 158, 234, 180, 234] as [UInt8]

/**
* Creates a _SetAndVerifyCollection_ instruction.
*
* @param accounts that will be accessed while the instruction is processed
* @category Instructions
* @category SetAndVerifyCollection
* @category generated
*/
public func createSetAndVerifyCollectionInstruction(accounts: SetAndVerifyCollectionInstructionAccounts, 
programId: PublicKey=PublicKey(string: "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s")!) -> TransactionInstruction {

    let data = SetAndVerifyCollectionStruct.serialize(
            instance: ["instructionDiscriminator": setAndVerifyCollectionInstructionDiscriminator ])

    var keys: [AccountMeta] = [
        AccountMeta(
            publicKey: accounts.metadata,
            isSigner: false,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.collectionAuthority,
            isSigner: true,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.payer,
            isSigner: true,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.updateAuthority,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.collectionMint,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.collection,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.collectionMasterEditionAccount,
            isSigner: false,
            isWritable: false
        )
    ]
    if accounts.collectionAuthorityRecord != nil {
        
        keys.append(
            AccountMeta(
                publicKey: accounts.collectionAuthorityRecord!,
                isSigner: false,
                isWritable: false
            )
        )
    }

    let ix = TransactionInstruction(
                keys: keys,
                programId: programId,
                data: data.0.bytes
            )
    return ix
}