/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita-swift
 */
import Foundation
import Beet
import Solana

/**
 * @category Instructions
 * @category SignMetadata
 * @category generated
 */
public struct SignMetadataInstructionArgs{
    let instructionDiscriminator: [UInt8] /* size: 8 */
    

    public init(
        instructionDiscriminator: [UInt8] /* size: 8 */ = signMetadataInstructionDiscriminator
    ) {
        self.instructionDiscriminator = instructionDiscriminator
    }
}
/**
 * @category Instructions
 * @category SignMetadata
 * @category generated
 */
public let SignMetadataStruct = FixableBeetArgsStruct<SignMetadataInstructionArgs>(
    fields: [
        ("instructionDiscriminator", Beet.fixedBeet(.init(value: .collection(UniformFixedSizeArray<UInt8>(element: .init(value: .scalar(u8())), len: 8))))),
        
    ],
    description: "SignMetadataInstructionArgs"
)
/**
* Accounts required by the _SignMetadata_ instruction
*
* @property [_writable_] metadata  
* @property [**signer**] creator   
* @category Instructions
* @category SignMetadata
* @category generated
*/
public struct SignMetadataInstructionAccounts {
    let metadata: PublicKey
    let creator: PublicKey

    public init(
        metadata: PublicKey,
        creator: PublicKey
    ) {
        self.metadata = metadata
        self.creator = creator
    }
}

public let signMetadataInstructionDiscriminator = [178, 245, 253, 205, 236, 250, 233, 209] as [UInt8]

/**
* Creates a _SignMetadata_ instruction.
*
* @param accounts that will be accessed while the instruction is processed
* @category Instructions
* @category SignMetadata
* @category generated
*/
public func createSignMetadataInstruction(accounts: SignMetadataInstructionAccounts, 
programId: PublicKey=PublicKey(string: "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s")!) -> TransactionInstruction {

    let data = SignMetadataStruct.serialize(
            instance: ["instructionDiscriminator": signMetadataInstructionDiscriminator ])

    let keys: [AccountMeta] = [
        AccountMeta(
            publicKey: accounts.metadata,
            isSigner: false,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.creator,
            isSigner: true,
            isWritable: false
        )
    ]

    let ix = TransactionInstruction(
                keys: keys,
                programId: programId,
                data: data.0.bytes
            )
    return ix
}