/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita-swift
 */
import Foundation
import Beet
import Solana

/**
 * @category Instructions
 * @category InitializeCandyMachine
 * @category generated
 */
public struct InitializeCandyMachineInstructionArgs{
    let instructionDiscriminator: [UInt8] /* size: 8 */
    let data: CandyMachineData
}
/**
 * @category Instructions
 * @category InitializeCandyMachine
 * @category generated
 */
public let initializeCandyMachineStruct = FixableBeetArgsStruct<InitializeCandyMachineInstructionArgs>(
    fields: [
        ("instructionDiscriminator", Beet.fixedBeet(.init(value: .collection(UniformFixedSizeArray<UInt8>(element: .init(value: .scalar(u8())), len: 8))))),
        ("data", candyMachineDataBeetWrapped)
    ],
    description: "InitializeCandyMachineInstructionArgs"
)
/**
* Accounts required by the _initializeCandyMachine_ instruction
*
* @property [_writable_] candyMachine  
* @property [] wallet  
* @property [] authority  
* @property [**signer**] payer   
* @category Instructions
* @category InitializeCandyMachine
* @category generated
*/
public struct InitializeCandyMachineInstructionAccounts {
        let candyMachine: PublicKey
        let wallet: PublicKey
        let authority: PublicKey
        let payer: PublicKey
        let systemProgram: PublicKey?
        let rent: PublicKey?
}

public let initializeCandyMachineInstructionDiscriminator = [103, 108, 111, 98, 97, 108, 58, 105] as [UInt8]

/**
* Creates a _InitializeCandyMachine_ instruction.
*
* @param accounts that will be accessed while the instruction is processed
  * @param args to provide as instruction data to the program
 * 
* @category Instructions
* @category InitializeCandyMachine
* @category generated
*/
public func createInitializeCandyMachineInstruction(accounts: InitializeCandyMachineInstructionAccounts, 
args: InitializeCandyMachineInstructionArgs, programId: PublicKey=PublicKey(string: "")!) -> TransactionInstruction {

    let data = initializeCandyMachineStruct.serialize(
            instance: ["instructionDiscriminator": initializeCandyMachineInstructionDiscriminator,
"data": args.data])

    let keys: [Account.Meta] = [
        Account.Meta(
            publicKey: accounts.candyMachine,
            isSigner: false,
            isWritable: true
        ),
        Account.Meta(
            publicKey: accounts.wallet,
            isSigner: false,
            isWritable: false
        ),
        Account.Meta(
            publicKey: accounts.authority,
            isSigner: false,
            isWritable: false
        ),
        Account.Meta(
            publicKey: accounts.payer,
            isSigner: true,
            isWritable: false
        ),
        Account.Meta(
            publicKey: accounts.systemProgram ?? PublicKey.systemProgramId,
            isSigner: false,
            isWritable: false
        ),
        Account.Meta(
            publicKey: accounts.rent ?? PublicKey.sysvarRent,
            isSigner: false,
            isWritable: false
        )
    ]

    let ix = TransactionInstruction(
                keys: keys,
                programId: programId,
                data: data.0.bytes
            )
    return ix
}