/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita-swift
 */
import Foundation
import Beet
import Solana
import BeetSolana

/**
 * @category Instructions
 * @category UpdateAuthority
 * @category generated
 */
public struct UpdateAuthorityInstructionArgs{
    let instructionDiscriminator: [UInt8] /* size: 8 */
    let newAuthority: COption<PublicKey>

    public init(
        instructionDiscriminator: [UInt8] /* size: 8 */ = updateAuthorityInstructionDiscriminator,
        newAuthority: COption<PublicKey>
    ) {
        self.instructionDiscriminator = instructionDiscriminator
        self.newAuthority = newAuthority
    }
}
/**
 * @category Instructions
 * @category UpdateAuthority
 * @category generated
 */
public let updateAuthorityStruct = FixableBeetArgsStruct<UpdateAuthorityInstructionArgs>(
    fields: [
        ("instructionDiscriminator", Beet.fixedBeet(.init(value: .collection(UniformFixedSizeArray<UInt8>(element: .init(value: .scalar(u8())), len: 8))))),
        ("newAuthority", Beet.fixableBeat(coption(inner: Beet.fixedBeet(.init(value: .scalar(BeetPublicKey()))))))
    ],
    description: "UpdateAuthorityInstructionArgs"
)
/**
* Accounts required by the _updateAuthority_ instruction
*
* @property [_writable_] candyMachine  
* @property [**signer**] authority  
* @property [] wallet   
* @category Instructions
* @category UpdateAuthority
* @category generated
*/
public struct UpdateAuthorityInstructionAccounts {
    let candyMachine: PublicKey
    let authority: PublicKey
    let wallet: PublicKey

    public init(
        candyMachine: PublicKey,
        authority: PublicKey,
        wallet: PublicKey
    ) {
        self.candyMachine = candyMachine
        self.authority = authority
        self.wallet = wallet
    }
}

public let updateAuthorityInstructionDiscriminator = [32, 46, 64, 28, 149, 75, 243, 88] as [UInt8]

/**
* Creates a _UpdateAuthority_ instruction.
*
* @param accounts that will be accessed while the instruction is processed
  * @param args to provide as instruction data to the program
 * 
* @category Instructions
* @category UpdateAuthority
* @category generated
*/
public func createUpdateAuthorityInstruction(accounts: UpdateAuthorityInstructionAccounts, 
args: UpdateAuthorityInstructionArgs, programId: PublicKey=PublicKey(string: "")!) -> TransactionInstruction {

    let data = updateAuthorityStruct.serialize(
            instance: ["instructionDiscriminator": updateAuthorityInstructionDiscriminator,
"newAuthority": args.newAuthority])

    let keys: [AccountMeta] = [
        AccountMeta(
            publicKey: accounts.candyMachine,
            isSigner: false,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.authority,
            isSigner: true,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.wallet,
            isSigner: false,
            isWritable: false
        )
    ]

    let ix = TransactionInstruction(
                keys: keys,
                programId: programId,
                data: data.0.bytes
            )
    return ix
}