/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita-swift
 */
import Foundation
import Beet
import BeetSolana
import Solana


/**
* Arguments used to create {@link Collectionauthorityrecord}
* @category Accounts
* @category generated
*/
public protocol CollectionauthorityrecordArgs {
    var collectionAuthorityRecordDiscriminator: [UInt8] { get }
     var key: Key { get }
     var bump: UInt8 { get }
}

/**
 * Holds the data for the {@link Collectionauthorityrecord} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
public struct Collectionauthorityrecord: CollectionauthorityrecordArgs {
  public static let collectionAuthorityRecordDiscriminator = [156, 48, 108, 31, 212, 219, 100, 168] as [UInt8]

  public let collectionAuthorityRecordDiscriminator: [UInt8]
  public let key: Key
  public let bump: UInt8

  /**
   * Creates a {@link Collectionauthorityrecord} instance from the provided args.
   */
  public static func fromArgs(args: Args) -> Collectionauthorityrecord {
    return Collectionauthorityrecord(
        collectionAuthorityRecordDiscriminator: args["accountDiscriminator"] as! [UInt8],
        key: args["key"] as! Key,
        bump: args["bump"] as! UInt8
    )
  }
  /**
   * Deserializes the {@link Collectionauthorityrecord} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  public static func fromAccountInfo(
    accountInfo: Foundation.Data,
    offset:Int=0
  ) -> ( Collectionauthorityrecord, Int )  {
    return Collectionauthorityrecord.deserialize(buf: accountInfo, offset: offset)
  }
  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link Collectionauthorityrecord} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  public static func fromAccountAddress(
    connection: Api,
    address: PublicKey,
    onComplete: @escaping (Result<Collectionauthorityrecord, Error>) -> Void
  ) {
    connection.getAccountInfo(account: address.base58EncodedString) { result in
        switch result {
            case .success(let pureData):
                if let data = pureData.data?.value {
                    onComplete(.success(Collectionauthorityrecord.deserialize(buf: data).0))
                } else {
                    onComplete(.failure(SolanaError.nullValue))
                }
            case .failure(let error):
                onComplete(.failure(error))
        }
    }
  }
  /**
   * Deserializes the {@link Collectionauthorityrecord} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  public static func deserialize(
    buf: Foundation.Data,
    offset: Int = 0
  ) -> ( Collectionauthorityrecord, Int ) {
    return collectionAuthorityRecordBeet.deserialize(buffer: buf, offset: offset)
  }
  /**
   * Serializes the {@link Collectionauthorityrecord} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  public func serialize() -> ( Foundation.Data, Int ) {
    return collectionAuthorityRecordBeet.serialize(instance: Collectionauthorityrecord(collectionAuthorityRecordDiscriminator : self.collectionAuthorityRecordDiscriminator,
        key : self.key,
        bump : self.bump))
  }
    /**
  * Returns the byteSize of a {@link Buffer} holding the serialized data of
  * {@link Collectionauthorityrecord}
  */
  static func byteSize() -> UInt {
      return collectionAuthorityRecordBeet.byteSize
  }
  /**
  * Fetches the minimum balance needed to exempt an account holding
  * {@link Collectionauthorityrecord} data from rent
  *
  * @param connection used to retrieve the rent exemption information
  */
  static func getMinimumBalanceForRentExemption(
      connection: Api,
      commitment: Commitment?,
      onComplete: @escaping(Result<UInt64, Error>) -> Void
  ) {
      return connection.getMinimumBalanceForRentExemption(dataLength: UInt64(Collectionauthorityrecord.byteSize()), commitment: commitment, onComplete: onComplete)
  }
  /**
  * Determines if the provided {@link Buffer} has the correct byte size to
  * hold {@link Collectionauthorityrecord} data.
  */
  static func hasCorrectByteSize(buf: Foundation.Data, offset:Int=0) -> Bool {
      return buf.bytes.count - offset == Collectionauthorityrecord.byteSize()
  }
}
  /**
   * @category Accounts
   * @category generated
   */
  public let collectionAuthorityRecordBeet = BeetStruct(
    fields:[
        ("accountDiscriminator", (.init(value: .collection(UniformFixedSizeArray<UInt8>(element: .init(value: .scalar(u8())), len: 8))))),
        ("key", keyBeet),
        ("bump", (.init(value: .scalar(u8()))))
    ],
    construct: Collectionauthorityrecord.fromArgs,
    description: "Collectionauthorityrecord"
)
