/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita-swift
 */
import Foundation
import Beet
import BeetSolana
import Solana


/**
* Arguments used to create {@link Edition}
* @category Accounts
* @category generated
*/
public protocol EditionArgs {
    var editionDiscriminator: [UInt8] { get }
     var key: Key { get }
     var parent: PublicKey { get }
     var edition: UInt64 { get }
}

/**
 * Holds the data for the {@link Edition} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
public struct Edition: EditionArgs {
  public static let editionDiscriminator = [234, 117, 249, 74, 7, 99, 235, 167] as [UInt8]

  public let editionDiscriminator: [UInt8]
  public let key: Key
  public let parent: PublicKey
  public let edition: UInt64

  /**
   * Creates a {@link Edition} instance from the provided args.
   */
  public static func fromArgs(args: Args) -> Edition {
    return Edition(
        editionDiscriminator: args["accountDiscriminator"] as! [UInt8],
        key: args["key"] as! Key,
        parent: args["parent"] as! PublicKey,
        edition: args["edition"] as! UInt64
    )
  }
  /**
   * Deserializes the {@link Edition} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  public static func fromAccountInfo(
    accountInfo: Foundation.Data,
    offset:Int=0
  ) -> ( Edition, Int )  {
    return Edition.deserialize(buf: accountInfo, offset: offset)
  }
  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link Edition} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  public static func fromAccountAddress(
    connection: Api,
    address: PublicKey,
    onComplete: @escaping (Result<Edition, Error>) -> Void
  ) {
    connection.getAccountInfo(account: address.base58EncodedString) { result in
        switch result {
            case .success(let pureData):
                if let data = pureData.data?.value {
                    onComplete(.success(Edition.deserialize(buf: data).0))
                } else {
                    onComplete(.failure(SolanaError.nullValue))
                }
            case .failure(let error):
                onComplete(.failure(error))
        }
    }
  }
  /**
   * Deserializes the {@link Edition} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  public static func deserialize(
    buf: Foundation.Data,
    offset: Int = 0
  ) -> ( Edition, Int ) {
    return editionBeet.deserialize(buffer: buf, offset: offset)
  }
  /**
   * Serializes the {@link Edition} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  public func serialize() -> ( Foundation.Data, Int ) {
    return editionBeet.serialize(instance: Edition(editionDiscriminator : self.editionDiscriminator,
        key : self.key,
        parent : self.parent,
        edition : self.edition))
  }
    /**
  * Returns the byteSize of a {@link Buffer} holding the serialized data of
  * {@link Edition}
  */
  static func byteSize() -> UInt {
      return editionBeet.byteSize
  }
  /**
  * Fetches the minimum balance needed to exempt an account holding
  * {@link Edition} data from rent
  *
  * @param connection used to retrieve the rent exemption information
  */
  static func getMinimumBalanceForRentExemption(
      connection: Api,
      commitment: Commitment?,
      onComplete: @escaping(Result<UInt64, Error>) -> Void
  ) {
      return connection.getMinimumBalanceForRentExemption(dataLength: UInt64(Edition.byteSize()), commitment: commitment, onComplete: onComplete)
  }
  /**
  * Determines if the provided {@link Buffer} has the correct byte size to
  * hold {@link Edition} data.
  */
  static func hasCorrectByteSize(buf: Foundation.Data, offset:Int=0) -> Bool {
      return buf.bytes.count - offset == Edition.byteSize()
  }
}
  /**
   * @category Accounts
   * @category generated
   */
  public let editionBeet = BeetStruct(
    fields:[
        ("accountDiscriminator", (.init(value: .collection(UniformFixedSizeArray<UInt8>(element: .init(value: .scalar(u8())), len: 8))))),
        ("key", keyBeet),
        ("parent", (.init(value: .scalar(BeetPublicKey())))),
        ("edition", (.init(value: .scalar(u64()))))
    ],
    construct: Edition.fromArgs,
    description: "Edition"
)
