/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita-swift
 */
import Foundation
import Beet
import BeetSolana
import Solana


/**
* Arguments used to create {@link Tokenownedescrow}
* @category Accounts
* @category generated
*/
public protocol TokenownedescrowArgs {
    
     var key: Key { get }
     var baseToken: PublicKey { get }
     var authority: EscrowAuthority { get }
     var bump: UInt8 { get }
}

/**
 * Holds the data for the {@link Tokenownedescrow} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
public struct Tokenownedescrow: TokenownedescrowArgs {
  

  public let key: Key
  public let baseToken: PublicKey
  public let authority: EscrowAuthority
  public let bump: UInt8

  /**
   * Creates a {@link Tokenownedescrow} instance from the provided args.
   */
  public static func fromArgs(args: Args) -> Tokenownedescrow {
    return Tokenownedescrow(
        key: args["key"] as! Key,
        baseToken: args["baseToken"] as! PublicKey,
        authority: args["authority"] as! EscrowAuthority,
        bump: args["bump"] as! UInt8
    )
  }
  /**
   * Deserializes the {@link Tokenownedescrow} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  public static func fromAccountInfo(
    accountInfo: Foundation.Data,
    offset:Int=0
  ) -> ( Tokenownedescrow, Int )  {
    return Tokenownedescrow.deserialize(buf: accountInfo, offset: offset)
  }
  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link Tokenownedescrow} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  public static func fromAccountAddress(
    connection: Api,
    address: PublicKey,
    onComplete: @escaping (Result<Tokenownedescrow, Error>) -> Void
  ) {
    connection.getAccountInfo(account: address.base58EncodedString) { result in
        switch result {
            case .success(let pureData):
                if let data = pureData.data?.value {
                    onComplete(.success(Tokenownedescrow.deserialize(buf: data).0))
                } else {
                    onComplete(.failure(SolanaError.nullValue))
                }
            case .failure(let error):
                onComplete(.failure(error))
        }
    }
  }
  /**
   * Deserializes the {@link Tokenownedescrow} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  public static func deserialize(
    buf: Foundation.Data,
    offset: Int = 0
  ) -> ( Tokenownedescrow, Int ) {
    return tokenOwnedEscrowBeet.deserialize(buffer: buf, offset: offset)
  }
  /**
   * Serializes the {@link Tokenownedescrow} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  public func serialize() -> ( Foundation.Data, Int ) {
    return tokenOwnedEscrowBeet.serialize(instance: Tokenownedescrow(key : self.key,
        baseToken : self.baseToken,
        authority : self.authority,
        bump : self.bump))
  }
    /**
  * Returns the byteSize of a {@link Buffer} holding the serialized data of
  * {@link Tokenownedescrow}
  */
  static func byteSize() -> UInt {
      return tokenOwnedEscrowBeet.byteSize
  }
  /**
  * Fetches the minimum balance needed to exempt an account holding
  * {@link Tokenownedescrow} data from rent
  *
  * @param connection used to retrieve the rent exemption information
  */
  static func getMinimumBalanceForRentExemption(
      connection: Api,
      commitment: Commitment?,
      onComplete: @escaping(Result<UInt64, Error>) -> Void
  ) {
      return connection.getMinimumBalanceForRentExemption(dataLength: UInt64(Tokenownedescrow.byteSize()), commitment: commitment, onComplete: onComplete)
  }
  /**
  * Determines if the provided {@link Buffer} has the correct byte size to
  * hold {@link Tokenownedescrow} data.
  */
  static func hasCorrectByteSize(buf: Foundation.Data, offset:Int=0) -> Bool {
      return buf.bytes.count - offset == Tokenownedescrow.byteSize()
  }
}
  /**
   * @category Accounts
   * @category generated
   */
  public let tokenOwnedEscrowBeet = BeetStruct(
    fields:[
        
        ("key", keyBeet),
        ("baseToken", (.init(value: .scalar(BeetPublicKey())))),
        ("authority", escrowAuthorityBeet),
        ("bump", (.init(value: .scalar(u8()))))
    ],
    construct: Tokenownedescrow.fromArgs,
    description: "Tokenownedescrow"
)
