/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita-swift
 */
import Foundation
import Beet
import Solana

/**
 * @category Instructions
 * @category InitializeV2
 * @category generated
 */
public struct InitializeV2InstructionArgs{
    let instructionDiscriminator: [UInt8] /* size: 8 */
    let data: CandyMachineData
    let tokenStandard: UInt8

    public init(
        instructionDiscriminator: [UInt8] /* size: 8 */ = initializeV2InstructionDiscriminator,
        data: CandyMachineData,
        tokenStandard: UInt8
    ) {
        self.instructionDiscriminator = instructionDiscriminator
        self.data = data
        self.tokenStandard = tokenStandard
    }
}
/**
 * @category Instructions
 * @category InitializeV2
 * @category generated
 */
public let initializeV2Struct = FixableBeetArgsStruct<InitializeV2InstructionArgs>(
    fields: [
        ("instructionDiscriminator", Beet.fixedBeet(.init(value: .collection(UniformFixedSizeArray<UInt8>(element: .init(value: .scalar(u8())), len: 8))))),
        ("data", candyMachineDataBeetWrapped),
        ("tokenStandard", Beet.fixedBeet(.init(value: .scalar(u8()))))
    ],
    description: "InitializeV2InstructionArgs"
)
/**
* Accounts required by the _initializeV2_ instruction
*
* @property [_writable_] candyMachine  
* @property [_writable_] authorityPda  
* @property [] authority  
* @property [_writable_, **signer**] payer  
* @property [] ruleSet  
* @property [_writable_] collectionMetadata  
* @property [] collectionMint  
* @property [] collectionMasterEdition  
* @property [_writable_, **signer**] collectionUpdateAuthority  
* @property [_writable_] collectionDelegateRecord  
* @property [] tokenMetadataProgram  
* @property [] sysvarInstructions  
* @property [] authorizationRulesProgram  
* @property [] authorizationRules   
* @category Instructions
* @category InitializeV2
* @category generated
*/
public struct InitializeV2InstructionAccounts {
    let candyMachine: PublicKey
    let authorityPda: PublicKey
    let authority: PublicKey
    let payer: PublicKey
    let ruleSet: PublicKey
    let collectionMetadata: PublicKey
    let collectionMint: PublicKey
    let collectionMasterEdition: PublicKey
    let collectionUpdateAuthority: PublicKey
    let collectionDelegateRecord: PublicKey
    let tokenMetadataProgram: PublicKey
    let systemProgram: PublicKey?
    let sysvarInstructions: PublicKey
    let authorizationRulesProgram: PublicKey
    let authorizationRules: PublicKey

    public init(
        candyMachine: PublicKey,
        authorityPda: PublicKey,
        authority: PublicKey,
        payer: PublicKey,
        ruleSet: PublicKey,
        collectionMetadata: PublicKey,
        collectionMint: PublicKey,
        collectionMasterEdition: PublicKey,
        collectionUpdateAuthority: PublicKey,
        collectionDelegateRecord: PublicKey,
        tokenMetadataProgram: PublicKey,
        systemProgram: PublicKey? = nil,
        sysvarInstructions: PublicKey,
        authorizationRulesProgram: PublicKey,
        authorizationRules: PublicKey
    ) {
        self.candyMachine = candyMachine
        self.authorityPda = authorityPda
        self.authority = authority
        self.payer = payer
        self.ruleSet = ruleSet
        self.collectionMetadata = collectionMetadata
        self.collectionMint = collectionMint
        self.collectionMasterEdition = collectionMasterEdition
        self.collectionUpdateAuthority = collectionUpdateAuthority
        self.collectionDelegateRecord = collectionDelegateRecord
        self.tokenMetadataProgram = tokenMetadataProgram
        self.systemProgram = systemProgram
        self.sysvarInstructions = sysvarInstructions
        self.authorizationRulesProgram = authorizationRulesProgram
        self.authorizationRules = authorizationRules
    }
}

public let initializeV2InstructionDiscriminator = [67, 153, 175, 39, 218, 16, 38, 32] as [UInt8]

/**
* Creates a _InitializeV2_ instruction.
*
* @param accounts that will be accessed while the instruction is processed
  * @param args to provide as instruction data to the program
 * 
* @category Instructions
* @category InitializeV2
* @category generated
*/
public func createInitializeV2Instruction(accounts: InitializeV2InstructionAccounts, 
args: InitializeV2InstructionArgs, programId: PublicKey=PublicKey(string: "CndyV3LdqHUfDLmE5naZjVN8rBZz4tqhdefbAnjHG3JR")!) -> TransactionInstruction {

    let data = initializeV2Struct.serialize(
            instance: ["instructionDiscriminator": initializeV2InstructionDiscriminator,
"data": args.data,
  "tokenStandard": args.tokenStandard])

    let keys: [AccountMeta] = [
        AccountMeta(
            publicKey: accounts.candyMachine,
            isSigner: false,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.authorityPda,
            isSigner: false,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.authority,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.payer,
            isSigner: true,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.ruleSet,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.collectionMetadata,
            isSigner: false,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.collectionMint,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.collectionMasterEdition,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.collectionUpdateAuthority,
            isSigner: true,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.collectionDelegateRecord,
            isSigner: false,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.tokenMetadataProgram,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.systemProgram ?? PublicKey.systemProgramId,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.sysvarInstructions,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.authorizationRulesProgram,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.authorizationRules,
            isSigner: false,
            isWritable: false
        )
    ]

    let ix = TransactionInstruction(
                keys: keys,
                programId: programId,
                data: data.0.bytes
            )
    return ix
}