/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita-swift
 */
import Foundation
import Beet
import Solana

/**
 * @category Instructions
 * @category Initialize
 * @category generated
 */
public struct InitializeInstructionArgs{
    let instructionDiscriminator: [UInt8] /* size: 8 */
    let data: CandyMachineData

    public init(
        instructionDiscriminator: [UInt8] /* size: 8 */ = initializeInstructionDiscriminator,
        data: CandyMachineData
    ) {
        self.instructionDiscriminator = instructionDiscriminator
        self.data = data
    }
}
/**
 * @category Instructions
 * @category Initialize
 * @category generated
 */
public let initializeStruct = FixableBeetArgsStruct<InitializeInstructionArgs>(
    fields: [
        ("instructionDiscriminator", Beet.fixedBeet(.init(value: .collection(UniformFixedSizeArray<UInt8>(element: .init(value: .scalar(u8())), len: 8))))),
        ("data", candyMachineDataBeetWrapped)
    ],
    description: "InitializeInstructionArgs"
)
/**
* Accounts required by the _initialize_ instruction
*
* @property [_writable_] candyMachine  
* @property [_writable_] authorityPda  
* @property [] authority  
* @property [**signer**] payer  
* @property [] collectionMetadata  
* @property [] collectionMint  
* @property [] collectionMasterEdition  
* @property [_writable_, **signer**] collectionUpdateAuthority  
* @property [_writable_] collectionAuthorityRecord  
* @property [] tokenMetadataProgram   
* @category Instructions
* @category Initialize
* @category generated
*/
public struct InitializeInstructionAccounts {
    let candyMachine: PublicKey
    let authorityPda: PublicKey
    let authority: PublicKey
    let payer: PublicKey
    let collectionMetadata: PublicKey
    let collectionMint: PublicKey
    let collectionMasterEdition: PublicKey
    let collectionUpdateAuthority: PublicKey
    let collectionAuthorityRecord: PublicKey
    let tokenMetadataProgram: PublicKey
    let systemProgram: PublicKey?

    public init(
        candyMachine: PublicKey,
        authorityPda: PublicKey,
        authority: PublicKey,
        payer: PublicKey,
        collectionMetadata: PublicKey,
        collectionMint: PublicKey,
        collectionMasterEdition: PublicKey,
        collectionUpdateAuthority: PublicKey,
        collectionAuthorityRecord: PublicKey,
        tokenMetadataProgram: PublicKey,
        systemProgram: PublicKey? = nil
    ) {
        self.candyMachine = candyMachine
        self.authorityPda = authorityPda
        self.authority = authority
        self.payer = payer
        self.collectionMetadata = collectionMetadata
        self.collectionMint = collectionMint
        self.collectionMasterEdition = collectionMasterEdition
        self.collectionUpdateAuthority = collectionUpdateAuthority
        self.collectionAuthorityRecord = collectionAuthorityRecord
        self.tokenMetadataProgram = tokenMetadataProgram
        self.systemProgram = systemProgram
    }
}

public let initializeInstructionDiscriminator = [175, 175, 109, 31, 13, 152, 155, 237] as [UInt8]

/**
* Creates a _Initialize_ instruction.
*
* @param accounts that will be accessed while the instruction is processed
  * @param args to provide as instruction data to the program
 * 
* @category Instructions
* @category Initialize
* @category generated
*/
public func createInitializeInstruction(accounts: InitializeInstructionAccounts, 
args: InitializeInstructionArgs, programId: PublicKey=PublicKey(string: "CndyV3LdqHUfDLmE5naZjVN8rBZz4tqhdefbAnjHG3JR")!) -> TransactionInstruction {

    let data = initializeStruct.serialize(
            instance: ["instructionDiscriminator": initializeInstructionDiscriminator,
"data": args.data])

    let keys: [AccountMeta] = [
        AccountMeta(
            publicKey: accounts.candyMachine,
            isSigner: false,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.authorityPda,
            isSigner: false,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.authority,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.payer,
            isSigner: true,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.collectionMetadata,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.collectionMint,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.collectionMasterEdition,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.collectionUpdateAuthority,
            isSigner: true,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.collectionAuthorityRecord,
            isSigner: false,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.tokenMetadataProgram,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.systemProgram ?? PublicKey.systemProgramId,
            isSigner: false,
            isWritable: false
        )
    ]

    let ix = TransactionInstruction(
                keys: keys,
                programId: programId,
                data: data.0.bytes
            )
    return ix
}