/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita-swift
 */
import Foundation
import Solana
import Beet

/**
 * @category Instructions
 * @category Mint
 * @category generated
 */
public struct MintInstructionArgs{
    let instructionDiscriminator: [UInt8] /* size: 8 */
    

    public init(
        instructionDiscriminator: [UInt8] /* size: 8 */ = mintInstructionDiscriminator
    ) {
        self.instructionDiscriminator = instructionDiscriminator
    }
}
/**
 * @category Instructions
 * @category Mint
 * @category generated
 */
public let mintStruct = FixableBeetArgsStruct<MintInstructionArgs>(
    fields: [
        ("instructionDiscriminator", Beet.fixedBeet(.init(value: .collection(UniformFixedSizeArray<UInt8>(element: .init(value: .scalar(u8())), len: 8))))),
        
    ],
    description: "MintInstructionArgs"
)
/**
* Accounts required by the _mint_ instruction
*
* @property [_writable_] candyMachine  
* @property [_writable_] authorityPda  
* @property [**signer**] mintAuthority  
* @property [_writable_, **signer**] payer  
* @property [_writable_] nftMint  
* @property [**signer**] nftMintAuthority  
* @property [_writable_] nftMetadata  
* @property [_writable_] nftMasterEdition  
* @property [] collectionAuthorityRecord  
* @property [] collectionMint  
* @property [_writable_] collectionMetadata  
* @property [] collectionMasterEdition  
* @property [] collectionUpdateAuthority  
* @property [] tokenMetadataProgram  
* @property [] recentSlothashes   
* @category Instructions
* @category Mint
* @category generated
*/
public struct MintInstructionAccounts {
    let candyMachine: PublicKey
    let authorityPda: PublicKey
    let mintAuthority: PublicKey
    let payer: PublicKey
    let nftMint: PublicKey
    let nftMintAuthority: PublicKey
    let nftMetadata: PublicKey
    let nftMasterEdition: PublicKey
    let collectionAuthorityRecord: PublicKey
    let collectionMint: PublicKey
    let collectionMetadata: PublicKey
    let collectionMasterEdition: PublicKey
    let collectionUpdateAuthority: PublicKey
    let tokenMetadataProgram: PublicKey
    let tokenProgram: PublicKey?
    let systemProgram: PublicKey?
    let recentSlothashes: PublicKey

    public init(
        candyMachine: PublicKey,
        authorityPda: PublicKey,
        mintAuthority: PublicKey,
        payer: PublicKey,
        nftMint: PublicKey,
        nftMintAuthority: PublicKey,
        nftMetadata: PublicKey,
        nftMasterEdition: PublicKey,
        collectionAuthorityRecord: PublicKey,
        collectionMint: PublicKey,
        collectionMetadata: PublicKey,
        collectionMasterEdition: PublicKey,
        collectionUpdateAuthority: PublicKey,
        tokenMetadataProgram: PublicKey,
        tokenProgram: PublicKey? = nil,
        systemProgram: PublicKey? = nil,
        recentSlothashes: PublicKey
    ) {
        self.candyMachine = candyMachine
        self.authorityPda = authorityPda
        self.mintAuthority = mintAuthority
        self.payer = payer
        self.nftMint = nftMint
        self.nftMintAuthority = nftMintAuthority
        self.nftMetadata = nftMetadata
        self.nftMasterEdition = nftMasterEdition
        self.collectionAuthorityRecord = collectionAuthorityRecord
        self.collectionMint = collectionMint
        self.collectionMetadata = collectionMetadata
        self.collectionMasterEdition = collectionMasterEdition
        self.collectionUpdateAuthority = collectionUpdateAuthority
        self.tokenMetadataProgram = tokenMetadataProgram
        self.tokenProgram = tokenProgram
        self.systemProgram = systemProgram
        self.recentSlothashes = recentSlothashes
    }
}

public let mintInstructionDiscriminator = [51, 57, 225, 47, 182, 146, 137, 166] as [UInt8]

/**
* Creates a _Mint_ instruction.
*
* @param accounts that will be accessed while the instruction is processed
* @category Instructions
* @category Mint
* @category generated
*/
public func createMintInstruction(accounts: MintInstructionAccounts, 
programId: PublicKey=PublicKey(string: "CndyV3LdqHUfDLmE5naZjVN8rBZz4tqhdefbAnjHG3JR")!) -> TransactionInstruction {

    let data = mintStruct.serialize(
            instance: ["instructionDiscriminator": mintInstructionDiscriminator ])

    let keys: [AccountMeta] = [
        AccountMeta(
            publicKey: accounts.candyMachine,
            isSigner: false,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.authorityPda,
            isSigner: false,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.mintAuthority,
            isSigner: true,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.payer,
            isSigner: true,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.nftMint,
            isSigner: false,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.nftMintAuthority,
            isSigner: true,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.nftMetadata,
            isSigner: false,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.nftMasterEdition,
            isSigner: false,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.collectionAuthorityRecord,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.collectionMint,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.collectionMetadata,
            isSigner: false,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.collectionMasterEdition,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.collectionUpdateAuthority,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.tokenMetadataProgram,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.tokenProgram ?? PublicKey.tokenProgramId,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.systemProgram ?? PublicKey.systemProgramId,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.recentSlothashes,
            isSigner: false,
            isWritable: false
        )
    ]

    let ix = TransactionInstruction(
                keys: keys,
                programId: programId,
                data: data.0.bytes
            )
    return ix
}