/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita-swift
 */
import Foundation
import Beet
import Solana
import BeetSolana

/**
 * @category Instructions
 * @category SetAuthority
 * @category generated
 */
public struct SetAuthorityInstructionArgs{
    let instructionDiscriminator: [UInt8] /* size: 8 */
    let newAuthority: PublicKey

    public init(
        instructionDiscriminator: [UInt8] /* size: 8 */ = setAuthorityInstructionDiscriminator,
        newAuthority: PublicKey
    ) {
        self.instructionDiscriminator = instructionDiscriminator
        self.newAuthority = newAuthority
    }
}
/**
 * @category Instructions
 * @category SetAuthority
 * @category generated
 */
public let setAuthorityStruct = FixableBeetArgsStruct<SetAuthorityInstructionArgs>(
    fields: [
        ("instructionDiscriminator", Beet.fixedBeet(.init(value: .collection(UniformFixedSizeArray<UInt8>(element: .init(value: .scalar(u8())), len: 8))))),
        ("newAuthority", Beet.fixedBeet(.init(value: .scalar(BeetPublicKey()))))
    ],
    description: "SetAuthorityInstructionArgs"
)
/**
* Accounts required by the _setAuthority_ instruction
*
* @property [_writable_] candyMachine  
* @property [**signer**] authority   
* @category Instructions
* @category SetAuthority
* @category generated
*/
public struct SetAuthorityInstructionAccounts {
    let candyMachine: PublicKey
    let authority: PublicKey

    public init(
        candyMachine: PublicKey,
        authority: PublicKey
    ) {
        self.candyMachine = candyMachine
        self.authority = authority
    }
}

public let setAuthorityInstructionDiscriminator = [133, 250, 37, 21, 110, 163, 26, 121] as [UInt8]

/**
* Creates a _SetAuthority_ instruction.
*
* @param accounts that will be accessed while the instruction is processed
  * @param args to provide as instruction data to the program
 * 
* @category Instructions
* @category SetAuthority
* @category generated
*/
public func createSetAuthorityInstruction(accounts: SetAuthorityInstructionAccounts, 
args: SetAuthorityInstructionArgs, programId: PublicKey=PublicKey(string: "CndyV3LdqHUfDLmE5naZjVN8rBZz4tqhdefbAnjHG3JR")!) -> TransactionInstruction {

    let data = setAuthorityStruct.serialize(
            instance: ["instructionDiscriminator": setAuthorityInstructionDiscriminator,
"newAuthority": args.newAuthority])

    let keys: [AccountMeta] = [
        AccountMeta(
            publicKey: accounts.candyMachine,
            isSigner: false,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.authority,
            isSigner: true,
            isWritable: false
        )
    ]

    let ix = TransactionInstruction(
                keys: keys,
                programId: programId,
                data: data.0.bytes
            )
    return ix
}