/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita-swift
 */
import Foundation
import Solana
import Beet

/**
 * @category Instructions
 * @category SetCollectionV2
 * @category generated
 */
public struct SetCollectionV2InstructionArgs{
    let instructionDiscriminator: [UInt8] /* size: 8 */
    

    public init(
        instructionDiscriminator: [UInt8] /* size: 8 */ = setCollectionV2InstructionDiscriminator
    ) {
        self.instructionDiscriminator = instructionDiscriminator
    }
}
/**
 * @category Instructions
 * @category SetCollectionV2
 * @category generated
 */
public let setCollectionV2Struct = FixableBeetArgsStruct<SetCollectionV2InstructionArgs>(
    fields: [
        ("instructionDiscriminator", Beet.fixedBeet(.init(value: .collection(UniformFixedSizeArray<UInt8>(element: .init(value: .scalar(u8())), len: 8))))),
        
    ],
    description: "SetCollectionV2InstructionArgs"
)
/**
* Accounts required by the _setCollectionV2_ instruction
*
* @property [_writable_] candyMachine  
* @property [**signer**] authority  
* @property [] authorityPda  
* @property [_writable_, **signer**] payer  
* @property [] collectionUpdateAuthority  
* @property [] collectionMint  
* @property [] collectionMetadata  
* @property [_writable_] collectionDelegateRecord  
* @property [**signer**] newCollectionUpdateAuthority  
* @property [] newCollectionMint  
* @property [] newCollectionMetadata  
* @property [] newCollectionMasterEdition  
* @property [_writable_] newCollectionDelegateRecord  
* @property [] tokenMetadataProgram  
* @property [] sysvarInstructions  
* @property [] authorizationRulesProgram  
* @property [] authorizationRules   
* @category Instructions
* @category SetCollectionV2
* @category generated
*/
public struct SetCollectionV2InstructionAccounts {
    let candyMachine: PublicKey
    let authority: PublicKey
    let authorityPda: PublicKey
    let payer: PublicKey
    let collectionUpdateAuthority: PublicKey
    let collectionMint: PublicKey
    let collectionMetadata: PublicKey
    let collectionDelegateRecord: PublicKey
    let newCollectionUpdateAuthority: PublicKey
    let newCollectionMint: PublicKey
    let newCollectionMetadata: PublicKey
    let newCollectionMasterEdition: PublicKey
    let newCollectionDelegateRecord: PublicKey
    let tokenMetadataProgram: PublicKey
    let systemProgram: PublicKey?
    let sysvarInstructions: PublicKey
    let authorizationRulesProgram: PublicKey
    let authorizationRules: PublicKey

    public init(
        candyMachine: PublicKey,
        authority: PublicKey,
        authorityPda: PublicKey,
        payer: PublicKey,
        collectionUpdateAuthority: PublicKey,
        collectionMint: PublicKey,
        collectionMetadata: PublicKey,
        collectionDelegateRecord: PublicKey,
        newCollectionUpdateAuthority: PublicKey,
        newCollectionMint: PublicKey,
        newCollectionMetadata: PublicKey,
        newCollectionMasterEdition: PublicKey,
        newCollectionDelegateRecord: PublicKey,
        tokenMetadataProgram: PublicKey,
        systemProgram: PublicKey? = nil,
        sysvarInstructions: PublicKey,
        authorizationRulesProgram: PublicKey,
        authorizationRules: PublicKey
    ) {
        self.candyMachine = candyMachine
        self.authority = authority
        self.authorityPda = authorityPda
        self.payer = payer
        self.collectionUpdateAuthority = collectionUpdateAuthority
        self.collectionMint = collectionMint
        self.collectionMetadata = collectionMetadata
        self.collectionDelegateRecord = collectionDelegateRecord
        self.newCollectionUpdateAuthority = newCollectionUpdateAuthority
        self.newCollectionMint = newCollectionMint
        self.newCollectionMetadata = newCollectionMetadata
        self.newCollectionMasterEdition = newCollectionMasterEdition
        self.newCollectionDelegateRecord = newCollectionDelegateRecord
        self.tokenMetadataProgram = tokenMetadataProgram
        self.systemProgram = systemProgram
        self.sysvarInstructions = sysvarInstructions
        self.authorizationRulesProgram = authorizationRulesProgram
        self.authorizationRules = authorizationRules
    }
}

public let setCollectionV2InstructionDiscriminator = [229, 35, 61, 91, 15, 14, 99, 160] as [UInt8]

/**
* Creates a _SetCollectionV2_ instruction.
*
* @param accounts that will be accessed while the instruction is processed
* @category Instructions
* @category SetCollectionV2
* @category generated
*/
public func createSetCollectionV2Instruction(accounts: SetCollectionV2InstructionAccounts, 
programId: PublicKey=PublicKey(string: "CndyV3LdqHUfDLmE5naZjVN8rBZz4tqhdefbAnjHG3JR")!) -> TransactionInstruction {

    let data = setCollectionV2Struct.serialize(
            instance: ["instructionDiscriminator": setCollectionV2InstructionDiscriminator ])

    let keys: [AccountMeta] = [
        AccountMeta(
            publicKey: accounts.candyMachine,
            isSigner: false,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.authority,
            isSigner: true,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.authorityPda,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.payer,
            isSigner: true,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.collectionUpdateAuthority,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.collectionMint,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.collectionMetadata,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.collectionDelegateRecord,
            isSigner: false,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.newCollectionUpdateAuthority,
            isSigner: true,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.newCollectionMint,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.newCollectionMetadata,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.newCollectionMasterEdition,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.newCollectionDelegateRecord,
            isSigner: false,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.tokenMetadataProgram,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.systemProgram ?? PublicKey.systemProgramId,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.sysvarInstructions,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.authorizationRulesProgram,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.authorizationRules,
            isSigner: false,
            isWritable: false
        )
    ]

    let ix = TransactionInstruction(
                keys: keys,
                programId: programId,
                data: data.0.bytes
            )
    return ix
}