/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita-swift
 */
import Foundation
import Solana
import Beet

/**
 * @category Instructions
 * @category Initialize
 * @category generated
 */
public struct InitializeInstructionArgs{
    let instructionDiscriminator: [UInt8] /* size: 8 */
    let data: Data

    public init(
        instructionDiscriminator: [UInt8] /* size: 8 */ = initializeInstructionDiscriminator,
        data: Data
    ) {
        self.instructionDiscriminator = instructionDiscriminator
        self.data = data
    }
}
/**
 * @category Instructions
 * @category Initialize
 * @category generated
 */
public let initializeStruct = FixableBeetArgsStruct<InitializeInstructionArgs>(
    fields: [
        ("instructionDiscriminator", Beet.fixedBeet(.init(value: .collection(UniformFixedSizeArray<UInt8>(element: .init(value: .scalar(u8())), len: 8))))),
        ("data", Beet.fixableBeat(Uint8Array()))
    ],
    description: "InitializeInstructionArgs"
)
/**
* Accounts required by the _initialize_ instruction
*
* @property [_writable_] candyGuard  
* @property [**signer**] base  
* @property [] authority  
* @property [_writable_, **signer**] payer   
* @category Instructions
* @category Initialize
* @category generated
*/
public struct InitializeInstructionAccounts {
    let candyGuard: PublicKey
    let base: PublicKey
    let authority: PublicKey
    let payer: PublicKey
    let systemProgram: PublicKey?

    public init(
        candyGuard: PublicKey,
        base: PublicKey,
        authority: PublicKey,
        payer: PublicKey,
        systemProgram: PublicKey? = nil
    ) {
        self.candyGuard = candyGuard
        self.base = base
        self.authority = authority
        self.payer = payer
        self.systemProgram = systemProgram
    }
}

public let initializeInstructionDiscriminator = [175, 175, 109, 31, 13, 152, 155, 237] as [UInt8]

/**
* Creates a _Initialize_ instruction.
*
* @param accounts that will be accessed while the instruction is processed
  * @param args to provide as instruction data to the program
 * 
* @category Instructions
* @category Initialize
* @category generated
*/
public func createInitializeInstruction(accounts: InitializeInstructionAccounts, 
args: InitializeInstructionArgs, programId: PublicKey=PublicKey(string: "Guard1JwRhJkVH6XZhzoYxeBVQe872VH6QggF4BWmS9g")!) -> TransactionInstruction {

    let data = initializeStruct.serialize(
            instance: ["instructionDiscriminator": initializeInstructionDiscriminator,
"data": args.data])

    let keys: [AccountMeta] = [
        AccountMeta(
            publicKey: accounts.candyGuard,
            isSigner: false,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.base,
            isSigner: true,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.authority,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.payer,
            isSigner: true,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.systemProgram ?? PublicKey.systemProgramId,
            isSigner: false,
            isWritable: false
        )
    ]

    let ix = TransactionInstruction(
                keys: keys,
                programId: programId,
                data: data.0.bytes
            )
    return ix
}