/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita-swift
 */
import Foundation
import Beet
import Solana

/**
 * @category Instructions
 * @category Wrap
 * @category generated
 */
public struct WrapInstructionArgs{
    let instructionDiscriminator: [UInt8] /* size: 8 */
    

    public init(
        instructionDiscriminator: [UInt8] /* size: 8 */ = wrapInstructionDiscriminator
    ) {
        self.instructionDiscriminator = instructionDiscriminator
    }
}
/**
 * @category Instructions
 * @category Wrap
 * @category generated
 */
public let wrapStruct = FixableBeetArgsStruct<WrapInstructionArgs>(
    fields: [
        ("instructionDiscriminator", Beet.fixedBeet(.init(value: .collection(UniformFixedSizeArray<UInt8>(element: .init(value: .scalar(u8())), len: 8))))),
        
    ],
    description: "WrapInstructionArgs"
)
/**
* Accounts required by the _wrap_ instruction
*
* @property [] candyGuard  
* @property [**signer**] authority  
* @property [_writable_] candyMachine  
* @property [] candyMachineProgram  
* @property [**signer**] candyMachineAuthority   
* @category Instructions
* @category Wrap
* @category generated
*/
public struct WrapInstructionAccounts {
    let candyGuard: PublicKey
    let authority: PublicKey
    let candyMachine: PublicKey
    let candyMachineProgram: PublicKey
    let candyMachineAuthority: PublicKey

    public init(
        candyGuard: PublicKey,
        authority: PublicKey,
        candyMachine: PublicKey,
        candyMachineProgram: PublicKey,
        candyMachineAuthority: PublicKey
    ) {
        self.candyGuard = candyGuard
        self.authority = authority
        self.candyMachine = candyMachine
        self.candyMachineProgram = candyMachineProgram
        self.candyMachineAuthority = candyMachineAuthority
    }
}

public let wrapInstructionDiscriminator = [178, 40, 10, 189, 228, 129, 186, 140] as [UInt8]

/**
* Creates a _Wrap_ instruction.
*
* @param accounts that will be accessed while the instruction is processed
* @category Instructions
* @category Wrap
* @category generated
*/
public func createWrapInstruction(accounts: WrapInstructionAccounts, 
programId: PublicKey=PublicKey(string: "Guard1JwRhJkVH6XZhzoYxeBVQe872VH6QggF4BWmS9g")!) -> TransactionInstruction {

    let data = wrapStruct.serialize(
            instance: ["instructionDiscriminator": wrapInstructionDiscriminator ])

    let keys: [AccountMeta] = [
        AccountMeta(
            publicKey: accounts.candyGuard,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.authority,
            isSigner: true,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.candyMachine,
            isSigner: false,
            isWritable: true
        ),
        AccountMeta(
            publicKey: accounts.candyMachineProgram,
            isSigner: false,
            isWritable: false
        ),
        AccountMeta(
            publicKey: accounts.candyMachineAuthority,
            isSigner: true,
            isWritable: false
        )
    ]

    let ix = TransactionInstruction(
                keys: keys,
                programId: programId,
                data: data.0.bytes
            )
    return ix
}